<a href="https://colab.research.google.com/github/kocurvik/edu/blob/master/3DV/labs/cv01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1. cvičenie** - Google Colab, Základy NumPy, Základná manipulácia s obrazom v OpenCV

V tomto notebooku si ukážeme ako pracovať v Google Colab a s poliami v NumPy.

## Google Colab

Google Colab (http://colab.research.google.com) je nespoplatnená služba na ktorej je možné spúštať tzv. ipython noteboky. Služba poskytuje k dispozícii aj výpočty na GPU a CPU. Pre využitie tejto služby je nutné mať Google účet. Tieto notebooky môžeme spúšťať aj lokálne pomocou príkazu `jupyter notebook` v zložke kde máme uložené ipynb súbory.

V notebookoch máme dva druhy buniek. Textové, ako napr. tento a kód. Bunky s kódom môžeme spúštať tlačidlom play naľavo od bunky, alebo v prostredí Colab naraz od prvej až po poslednú výberom Runtime -> Run All. Defaultne notebook nemá pripojené GPU, to môžeme zmeniť zavolaním Runtime -> Change runtime type. Bunky majú spoločný scope ale je treba dávať pozor na poradie spúštania jednotlivých buniek. Preto je často vhodné použiť Runtime -> Restart and run all.

V nasledujúcej bunke si môžete otestovať spustenie python kódu.

In [ ]:
a = [5,'Hello']
s = '{} World!'
print(s.format(a[1]))

def najlepsia_funkcia(arg):
  return arg + 5

print(najlepsia_funkcia(8))

Hello World!
13


Keď sme v Google Colab chceli by sme mať prístup k súborom. To je najjednoduchšie pomocou pripojenia Google Drive k našej inštancii. To sa robí následovne:
(V Google Drive si vyrobte zložku Colab, alebo upravte na drive)

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')
root_path = 'gdrive/My Drive/Colab/'

Mounted at /content/gdrive


Môžeme potom k zložke pristupovať.

In [ ]:
import os
os.listdir(root_path)

['mnist-fc-trained.h5', 'cifar-fc-trained.h5']

Takisto môžeme volať unixové príkazy pomocou výkričníka.

In [ ]:
!pwd
!ls
!mkdir random_dir
!ls
!wget https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png
!ls

/content
gdrive	sample_data
gdrive	random_dir  sample_data
--2023-02-14 17:37:07--  https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png
Resolving www.google.com (www.google.com)... 108.177.98.105, 108.177.98.147, 108.177.98.106, ...
Connecting to www.google.com (www.google.com)|108.177.98.105|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5969 (5.8K) [image/png]
Saving to: ‘googlelogo_color_272x92dp.png’

googlelogo_color_27 100%[===================>]   5.83K  --.-KB/s    in 0s      

2023-02-14 17:37:07 (63.3 MB/s) - ‘googlelogo_color_272x92dp.png’ saved [5969/5969]

gdrive	googlelogo_color_272x92dp.png  random_dir  sample_data


Najpohodlnejšia možnosť je použiť inferface naľovo a pozrieť si záložku Files

**<----**

## NumPy

Pri práci budeme veľmi často používať NumPy. Jeho základnou štruktúrou je pole. Polia obecne môžu reprezentovať vektory, matice a tenzory vyšších rádov. Napr. množinu matíc, ktoré majú rovnaké rozmery môžeme reprezentovať ako pole tretieho rádu.

Podľa konvencie sa numpy väčšinou importuje ako np. 

Vektor, teda 1-rozmerné pole, vieme vyrobiť z jednuchého listu. Pomocou np.array. Často je dôležité použiť správny dátový typ to urobíme pomocou argumentu dtype. **Vynechanie tejto časti môže viesť na rôzne komplikácie!**

In [ ]:
import numpy as np

a = np.array([3, 2, 3, 4])
print(a)
b = np.array([1,5,7], dtype=np.float32)
print(b)

[3 2 3 4]
[1. 5. 7.]


Maticu vieme vyrobiť z listu listov, ale treba dať pozor aby nám sedeli dĺžky vnútorných listov. Inak sa vytvorí tenzor prvého rádu, ktorý obsahuje listy.

In [ ]:
A = np.array([[1,5,8],[50,60,84]])
print(A)
B = np.array([[7,8],[6,7],[0,9,4]])
print(B)

[[ 1  5  8]
 [50 60 84]]
[list([7, 8]) list([6, 7]) list([0, 9, 4])]


<ipython-input-6-575e0ddf66be>:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  B = np.array([[7,8],[6,7],[0,9,4]])


Objekt array má metódu shape, ktorá nám umožňuje zistiť jej tvar (teda dimenzie), metódu dtype ktorá vracia typ vnútorných objektov a metódu astype, ktorá vráti tenzor v podľa špecifikovaného typu.

In [ ]:
print(a.shape)
print(A.shape)
print(A.dtype)
C = A.astype(np.float32)
print(C.dtype)


(4,)
(2, 3)
int64
float32


Numpy má aj funkcie na tvorenie základných matíc. Tieto príkazy sú np.zeros, np.ones a np.empty.

In [ ]:
z = np.zeros([5,10])
print(z)
o = np.ones([3,4,5])
print(o)
e = np.empty([6])
print(e)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
[6.9094632e-310 6.9094632e-310 0.0000000e+000 0.0000000e+000
 0.0000000e+000 0.0000000e+000]


Je možné tvoriť aj náhodné čísla pomocou np.random.random

In [ ]:
r = np.random.random([6,10,3])
print(r)

[[[9.95885323e-01 4.03597882e-01 5.61389304e-01]
  [8.56023512e-01 9.40495021e-01 8.05226781e-01]
  [2.43896556e-01 3.82036415e-01 2.46050462e-01]
  [2.98728593e-01 8.44087912e-02 4.05704805e-01]
  [1.68945395e-01 7.05724802e-01 9.76466894e-01]
  [7.88578557e-01 4.71930249e-01 7.26157603e-01]
  [7.19493018e-01 1.73281562e-02 2.49157839e-01]
  [6.03709597e-01 3.00589632e-01 9.09663069e-01]
  [1.36333032e-01 8.30183231e-01 3.08378048e-01]
  [1.69389601e-02 7.54068197e-02 6.45319482e-01]]

 [[1.87452800e-01 1.50459858e-01 5.05246639e-01]
  [6.95681806e-02 2.91455984e-02 4.84858187e-01]
  [1.98130286e-01 6.45855300e-01 5.26166199e-01]
  [7.88006884e-01 5.79224394e-01 4.89390287e-01]
  [3.22805102e-01 6.73595179e-01 1.31740351e-01]
  [6.10207937e-01 8.47704612e-01 4.51704552e-01]
  [7.73975149e-01 6.00129740e-01 1.53249387e-01]
  [2.42028746e-01 8.35834051e-01 6.00285776e-02]
  [2.94400399e-01 3.00265876e-01 9.56334935e-01]
  [6.93344472e-01 6.80876497e-01 7.76266594e-04]]

 [[6.76340327e-0

Tieto náhodné čísla použijeme na prácu s indexmi. Indexácia je podobná ako v matlabe, ale platia tu pythonovské konvencie. Indexuje sa viacerými indexmi. Ak sa indexuje menej indexmi, tak sa tie ostatné berú ako :, čo znamená zobartie všetkých prvkov pozdĺž dimenzie.

In [ ]:
print(r[3,4,1])
print(r[:,:,-1])
print(r[:,:,1].shape)
print(r[0:4,5:6,:])
print(r[0:4,5:6,:].shape)

0.48874025140132116
[[5.61389304e-01 8.05226781e-01 2.46050462e-01 4.05704805e-01
  9.76466894e-01 7.26157603e-01 2.49157839e-01 9.09663069e-01
  3.08378048e-01 6.45319482e-01]
 [5.05246639e-01 4.84858187e-01 5.26166199e-01 4.89390287e-01
  1.31740351e-01 4.51704552e-01 1.53249387e-01 6.00285776e-02
  9.56334935e-01 7.76266594e-04]
 [2.06830816e-01 4.50087948e-01 5.86766195e-01 5.77688538e-01
  8.67448708e-01 4.91756426e-01 8.40781992e-01 8.51206855e-01
  4.29040890e-01 9.87689932e-01]
 [3.47900429e-01 8.98975385e-01 2.60258827e-01 1.36463669e-02
  5.49438695e-01 7.34609299e-01 5.56546121e-01 4.26063511e-01
  5.92313612e-01 4.48431490e-03]
 [1.11736753e-02 5.91502374e-01 3.56943509e-01 9.72695300e-01
  6.72601180e-01 6.38878924e-01 1.68058145e-01 9.46708054e-01
  8.44204130e-01 4.74868474e-01]
 [4.31651297e-01 8.04901070e-01 1.12391550e-01 2.90090385e-01
  9.28557957e-01 1.88986053e-01 9.82302323e-01 2.40586761e-01
  2.12326876e-01 7.56431027e-01]]
(6, 10)
[[[0.78857856 0.47193025 0.72

Indexovať môžeme aj s preskakovaním jednotlivých prvkov, tzv. slicing. To sa robí pomocou ďalšej dvojbodky. Formát je potom \[začiatok:koniec:skok\]. Ak niečo z toho vynecháme, tak žačiatok bude defaultne 0, koniec -1 a skok 1.

In [ ]:
p = np.arange(25)
print(p)
print(p[4:16:2])
print(p[2:-4:6])
print(p[:10:])
print(p[::3])
print(p[1::6])
print(p[-6:])
print(r[1::2,0::3,:])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[ 4  6  8 10 12 14]
[ 2  8 14 20]
[0 1 2 3 4 5 6 7 8 9]
[ 0  3  6  9 12 15 18 21 24]
[ 1  7 13 19]
[19 20 21 22 23 24]
[[[1.87452800e-01 1.50459858e-01 5.05246639e-01]
  [7.88006884e-01 5.79224394e-01 4.89390287e-01]
  [7.73975149e-01 6.00129740e-01 1.53249387e-01]
  [6.93344472e-01 6.80876497e-01 7.76266594e-04]]

 [[5.49469380e-02 7.61658822e-01 3.47900429e-01]
  [7.63691223e-01 3.78698873e-02 1.36463669e-02]
  [6.52932774e-01 5.95446557e-01 5.56546121e-01]
  [4.64085705e-01 4.49671253e-02 4.48431490e-03]]

 [[4.45000198e-01 2.19477514e-01 4.31651297e-01]
  [1.41873952e-01 3.81435863e-01 2.90090385e-01]
  [3.95852965e-01 8.83257081e-01 9.82302323e-01]
  [5.96032353e-01 4.18650869e-01 7.56431027e-01]]]


Niekedy potrebujeme vytvoriť tzv. singleton dimenziu. To znamená že zvýšime rád zvoleného tenzoru o jedna pričom novovzniknutá osa (axis) bude mať dimenziu jedna. Toto je užitočné najmä ak potrebujeme používať broadcasting pri rôznych operáciách.

In [ ]:
print(r[None,:,:,:].shape)
print(r[None].shape)
print(r[np.newaxis,:,:,:].shape)
print(r[:,:,:,np.newaxis].shape)
print(r[np.newaxis,:,0,:].shape)

(1, 6, 10, 3)
(1, 6, 10, 3)
(1, 6, 10, 3)
(6, 10, 3, 1)
(1, 6, 3)


Teraz môžeme vidieť v akcii aj broadcasting.

In [ ]:
r += 10
print(r)
r[0,:,:] = np.random.random([10,3])
print(r.shape)
r[0] = np.random.random([10,3])
print(r.shape)
r[0] = np.zeros([10,1])
print(r.shape)
r/=500
print(r)

[[[10.99588532 10.40359788 10.5613893 ]
  [10.85602351 10.94049502 10.80522678]
  [10.24389656 10.38203642 10.24605046]
  [10.29872859 10.08440879 10.40570481]
  [10.16894539 10.7057248  10.97646689]
  [10.78857856 10.47193025 10.7261576 ]
  [10.71949302 10.01732816 10.24915784]
  [10.6037096  10.30058963 10.90966307]
  [10.13633303 10.83018323 10.30837805]
  [10.01693896 10.07540682 10.64531948]]

 [[10.1874528  10.15045986 10.50524664]
  [10.06956818 10.0291456  10.48485819]
  [10.19813029 10.6458553  10.5261662 ]
  [10.78800688 10.57922439 10.48939029]
  [10.3228051  10.67359518 10.13174035]
  [10.61020794 10.84770461 10.45170455]
  [10.77397515 10.60012974 10.15324939]
  [10.24202875 10.83583405 10.06002858]
  [10.2944004  10.30026588 10.95633493]
  [10.69334447 10.6808765  10.00077627]]

 [[10.67634033 10.66055005 10.20683082]
  [10.44598496 10.01647829 10.45008795]
  [10.7605673  10.59826533 10.58676619]
  [10.12811432 10.53543504 10.57768854]
  [10.72101338 10.83323678 10.867448

Je možné polia pretvarovať pomocou np.reshape(arr, shape)

In [ ]:
q = np.reshape(r, [6,30])
print(q.shape)

(6, 30)


Polia môžeme spájať. Jeden spôsob je pomocou np.concatenate([arr1, arr2, ...], axis = i) t=a spojí arr1, arr2 atď. vedľa seba pozdĺž osy i.

In [ ]:
a = np.ones([3,4])
b = np.zeros([6,4])
c = np.concatenate([a,b], axis = 0)
print(c)                   

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Iný spôsob je použitie np.stack([arr1, arr2, ...], axis = i) narozdiel od cocatenate sa pri tomto príkaze vytvorí nová dimenzia poďľa hodnoty i. Existujú aj príkazy column_stack a row_stack.

In [ ]:
a = np.ones([6,4,3])
b = np.zeros([6,4,3])
d = np.stack([a,b], axis = 0)
print(d.shape)
f = np.stack([a,b], axis = -1)
print(f.shape)
g = np.stack([a,b], axis = 1)
print(g.shape)

(2, 6, 4, 3)
(6, 4, 3, 2)
(6, 2, 4, 3)


Indexovať môžeme aj pomocou podmienok.

In [ ]:
r = np.random.random([5,5])
print(r)
r[r < 0.5] = -500
print(r)

[[0.60643544 0.66730293 0.47275109 0.158011   0.24068463]
 [0.7151493  0.54554022 0.92186819 0.24924769 0.67270316]
 [0.80514547 0.03956551 0.58889968 0.85724311 0.96189877]
 [0.82354398 0.99771929 0.11239969 0.52785598 0.94681576]
 [0.76045869 0.7915977  0.85621659 0.48104025 0.90530371]]
[[   0.60643544    0.66730293 -500.         -500.         -500.        ]
 [   0.7151493     0.54554022    0.92186819 -500.            0.67270316]
 [   0.80514547 -500.            0.58889968    0.85724311    0.96189877]
 [   0.82354398    0.99771929 -500.            0.52785598    0.94681576]
 [   0.76045869    0.7915977     0.85621659 -500.            0.90530371]]


Podmienky môžeme použiť aj np.where(cond, a1, a2), ktorá vráti pole ktoré ma na miestach kde je cond splnená hodnoty z a1 a inde hodnoty z a2. Použijeme tu príkaz np.arange(i), ktorý vráti pole podobne ako range z pythonu.

In [ ]:
a = np.arange(10)
print(a)
b = np.where(a < 5, a, a**2)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4 25 36 49 64 81]


### Úloha - Chessboard
Vytvorte funkciu chessboard(rows, cols), ktorá vráti numpy pole s riadkami rows a stĺpcami cols ktorá bude mať hodnoty 0 a 1 na takých miestach ako sú farby na šachovnici. Môžete použiť slicing, podmienky (zíde sa vám np.mgrid), alebo opakovanie matíc (np.tile)

In [ ]:
def chessboard(rows, cols):
  ...

In [ ]:
print(chessboard(8,8))
print(chessboard(5,12))

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]
[[0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]]


### Úloha - Indexovanie

Vygenerujte náhodnú maticu s rozmermi 10 x 5 z rovnomerného rozdelenia. Následne zmente všetky prvky väčšie ako 0.8 na 1. Následne zmenťe všetky prvky menšie ako 0.3 na polovicu hodnoty na rovnakom riadku ale, vo vedľajšom stĺpci naľavo. Ak sú takéto hodnoty v prvom stĺpci, tak ich zmeňte na 0. Operáciu urobte tak, ako keby ste robili všetky zmeny naraz. V kóde to však nemusí byť jedna operácia. Budete potrebovať logickú indexáciu a v druhom prípade aj np.where. Nepoužite for cyklus.

In [ ]:
...

[[0.74027528 0.14235702 0.39665901 0.3891523  0.63451825]
 [0.97718423 0.99715736 0.63067475 0.80476931 0.14784647]
 [0.51975634 0.27866818 0.50297632 0.70019818 0.80967778]
 [0.67990934 0.20306608 0.48427877 0.74989176 0.41986531]
 [0.91891413 0.52045535 0.99755539 0.22745818 0.95593381]
 [0.40821301 0.07608976 0.06450501 0.2251722  0.72046368]
 [0.85837094 0.45988644 0.19681961 0.00892276 0.02556175]
 [0.2825981  0.64956695 0.42169434 0.10618065 0.29772611]
 [0.31136082 0.14418991 0.19083763 0.54011873 0.91688343]
 [0.24608039 0.02030628 0.642102   0.12799292 0.89714453]]
[[0.74027528 0.14235702 0.39665901 0.3891523  0.63451825]
 [1.         1.         0.63067475 1.         0.14784647]
 [0.51975634 0.27866818 0.50297632 0.70019818 1.        ]
 [0.67990934 0.20306608 0.48427877 0.74989176 0.41986531]
 [1.         0.52045535 1.         0.22745818 1.        ]
 [0.40821301 0.07608976 0.06450501 0.2251722  0.72046368]
 [1.         0.45988644 0.19681961 0.00892276 0.02556175]
 [0.2825981  

## Matematické operácie

Na polia môžeme aplikovať tiež matematické operácie.

In [ ]:
r = np.random.rand(10, 2)

In [ ]:
print(np.sin(r))
print(np.cos(r))
print(np.arccos(r))
print(np.exp(r))
print(r ** 2)

[[0.25497608 0.18381108]
 [0.65433683 0.50759631]
 [0.29732452 0.31978364]
 [0.82187733 0.81683468]
 [0.50736414 0.47060857]
 [0.21030374 0.59490437]
 [0.08434235 0.12025903]
 [0.45910469 0.73792798]
 [0.37733773 0.58111117]
 [0.01367389 0.05020922]]
[[0.96694736 0.98296159]
 [0.75620322 0.86159502]
 [0.95477648 0.94749059]
 [0.56966451 0.57687183]
 [0.86173176 0.8823421 ]
 [0.9776361  0.80379649]
 [0.99643684 0.99274255]
 [0.88838217 0.67487947]
 [0.92607572 0.81382419]
 [0.99990651 0.99873872]]
[[1.31002801 1.38486469]
 [0.77659324 1.0093717 ]
 [1.26412262 1.23925465]
 [0.26649932 0.29807884]
 [1.00968998 1.0587291 ]
 [1.35729232 0.88000581]
 [1.48625298 1.44995161]
 [1.07357276 0.59169765]
 [1.17350744 0.90193458]
 [1.55712158 1.52054484]]
[[1.2941097  1.20305264]
 [2.04072536 1.70300217]
 [1.35241139 1.3847244 ]
 [2.62399701 2.60101685]
 [1.70254337 1.63228417]
 [1.23600652 1.89107731]
 [1.08811046 1.12811805]
 [1.61121273 2.29330722]
 [1.47243842 1.85910167]
 [1.01376824 1.0515132

## Súhrnné operácie
Na numpy poliach je možné robiť aj rôzne operácie. Je napríklad možné sčítať pole pomocou príkazu np.sum. Podobne fungujú aj príkazy np.min (mininum), np.max(maximum), np.mean (priemer), np.median (medián), np.var (variácia) a np.std (štandardná odchýlka).



In [ ]:
a = np.random.rand(4, 3)
print(a)
print(np.mean(a))
print(np.median(a))
print(np.sum(a))
print(np.max(a))
print(np.std(a))

[[0.37916405 0.16916984 0.39551444]
 [0.12436263 0.48460161 0.58490869]
 [0.88752807 0.69104601 0.1736372 ]
 [0.65177933 0.16806973 0.44024125]]
0.4291685708661899
0.4178778445758962
5.150022850394279
0.8875280744068558
0.23332508195234322


## Kľučové slovo axis

Často chceme operáciu napr. sčítanie realizovať len po nejakej dimenzii. V takom prípade je vhodné využiť kľučové slovo axis. To nám umožní sčítavať po konkrétnej dimenzii. Je možné použiť aj tuple dimenzii po ktorých je možné sčítavať. Veľa numpy príkazov má tento keyword k dispozícii a je vhodné sa ho dobre naučiť používať.


In [ ]:
print(a)
print(np.sum(a, axis=0))
print(np.sum(a, axis=0).shape)
print(np.sum(a, axis=1))
print(np.sum(a, axis=1).shape)

b = np.random.rand(4,3,16,16)
print(np.sum(b, axis=(1,2,3)))
print(np.sum(b, axis=(1,2,3)).shape)

[[0.37916405 0.16916984 0.39551444]
 [0.12436263 0.48460161 0.58490869]
 [0.88752807 0.69104601 0.1736372 ]
 [0.65177933 0.16806973 0.44024125]]
[2.04283408 1.5128872  1.59430157]
(3,)
[0.94384834 1.19387292 1.75221128 1.26009031]
(4,)
[383.11871274 383.92771032 390.54336026 386.73048269]
(4,)


Pre minimum a maximum existujú ešte dve funkcie (np.minimum a np.maximum), ktoré porovnajú dve polia.

In [ ]:
b = ((np.arange(12) - 7) * 2).reshape(4,3)
print(b)
print(np.maximum(a, b))

[[-14 -12 -10]
 [ -8  -6  -4]
 [ -2   0   2]
 [  4   6   8]]
[[0.37916405 0.16916984 0.39551444]
 [0.12436263 0.48460161 0.58490869]
 [0.88752807 0.69104601 2.        ]
 [4.         6.         8.        ]]


### Úloha - Euklidovksá metrika

Implementujte funkciu euclidian_distance_single(x, y), ktorá na vstupe príjme dva vektory x a y, ktoré sú oba z $\mathbb{R}^n$ a vypočíta:

$$\rho_e(\vec{x}, \vec{y}) = \sqrt{\sum_{i=1}^{n} \left(x_i - y_i\right)^2}$$

In [ ]:
def euclidian_distance_single(x, y):
  ...

Kód môžeme otestovať pomocou funkcie np.linalg.norm, ktorá ráta to isté:

In [ ]:
for i in range(10):
  n = np.random.randint(100)
  a = np.random.rand(n)
  b = np.random.rand(n)

  d = euclidian_distance_single(a, b)
  d_gt = np.linalg.norm(a - b)
  if np.abs(d_gt - d) < 1e-8:
    print("Pass!")
  else:
    print("Fail")

Pass!
Pass!
Pass!
Pass!
Pass!
Pass!
Pass!
Pass!
Pass!
Pass!


### Úloha - Euklidovská metrika - vektorizovane

Teraz vytvoríme novú funkciu euclidian distance, ktorá bude fungovať tak, že x bude vektor $\mathbb{R}^n$ a y bude matica $m \times n$, ktorej každý riadok je vektor z $\mathbb{R}^n$. Funkcia potom vráti vektor dĺžky $m$, ktorý bude obsahovať metriky medzi x a jednotlivými vektormi z y.

In [ ]:
def euclidian_distance(x, y):
  ...

Kód otestujeme:

In [ ]:
for i in range(10):
  n = np.random.randint(100)
  a = np.random.rand(n)
  b = np.random.rand(30, n)

  d = euclidian_distance(a, b)

  for i in [4,9,13,24]:
    if np.abs(np.linalg.norm(a - b[i]) - d[i]) < 1e-8:
      print("Pass!")
    else:
      print("Fail!")

Pass!
Pass!
Pass!
Pass!
Pass!
Pass!
Pass!
Pass!
Pass!
Pass!
Pass!
Pass!
Pass!
Pass!
Pass!
Pass!
Pass!
Pass!
Pass!
Pass!
Pass!
Pass!
Pass!
Pass!
Pass!
Pass!
Pass!
Pass!
Pass!
Pass!
Pass!
Pass!
Pass!
Pass!
Pass!
Pass!
Pass!
Pass!
Pass!
Pass!


## Násobenie

Polia môžeme tiež násobiť. Môžeme použiť buď operátor `*`, ktorý realizuje násobenie po elementoch, alebo operátor `@`, ktorý realizuje maticové násobenie. V prípade `@` sa vektor vždy považuje za stĺpcový, alebo riadkový podľa toho čo sa hodí. Tiež je na násobenie možné použiť `np.dot`. Matice môžeme tiež transponovať metódou `.T`

In [ ]:
x = np.array([1, 2, 3])
y = np.array([8, 0, 7])

A = np.arange(9).reshape(3, 3)
B = np.random.rand(4, 3)
C = np.random.rand(3, 3)

print(x @ y)
print(x * y)

print(20 * '*')

print(A @ x)
print(y @ A)
print(x @ C)
print(x @ A @ y)

print(20 * '*')

print(A * C)
print(A @ C)
print(B @ A)

print(20 * '*')

#pri nasobeni po prvkoch moze dojst k broadcastingu
print(A * x)

print(20 * '*')

#tieto nebudu fungovat
print(x @ B)
print(A @ B)

29
[ 8  0 21]
********************
[ 8 26 44]
[42 57 72]
[3.209014   2.61309655 2.90003168]
444
********************
[[0.         0.59483341 0.84670845]
 [1.88196912 1.80193105 3.9677832 ]
 [2.65265204 2.60702777 2.37217112]]
[[ 1.51154039  1.19534784  1.38659942]
 [ 6.60396123  5.44859396  5.92689619]
 [11.69638207  9.70184008 10.46719296]]
[[ 3.18793161  4.23111949  5.27430737]
 [ 6.96202537  8.8518261  10.74162683]
 [ 8.1980496  10.46093128 12.72381296]
 [ 0.82629048  1.97569068  3.12509088]]
********************
[[ 0  2  6]
 [ 3  8 15]
 [ 6 14 24]]
********************


ValueError: ignored

### Úloha - Lineárny Systém.

Môžeme tiež definovať lineárne systémy. Využiť potom na riešenie môžeme funckiu np.linalg.solve. Naštudujte si ju v dokumentácii a použite ju na riešenie úlohy z obrázku:

![](https://www.lifehacker.com.au/wp-content/uploads/sites/4/2016/02/Fruit.jpg)

In [ ]:
...

Linear system has a solution:  [10.  1.  1.]
The problem then has a solution:  14.0


### Úloha - Lineárny systém pomocou SVD

Urobte to isté pomocou SVD, tak že použijete postup z prednášky na vytvorenie pseudoinverznej matice (v tomto prípade to bude zároveň matica inverzná) a následne vyžijete že $A^{-1}\vec{b} = \vec{x}$.

In [ ]:
...

Linear system has a solution:  [10.  1.  1.]
The problem then has a solution:  13.999999999999998


### Úloha SVD

Teraz použite SVD a pre maticu A zistite aké má jadro a hodnosť. Nezabudnite, že pracujeme s floatami.

In [ ]:
A = np.array([[4, 5, 3, 0], [1, 0, 0, 1], [9, 10, 6, 1], [1, 1, 0, 0], [7, 1, 0, 6]])
print(A)

[[ 4  5  3  0]
 [ 1  0  0  1]
 [ 9 10  6  1]
 [ 1  1  0  0]
 [ 7  1  0  6]]


In [ ]:
...

[1.74360183e+01 7.32500489e+00 5.74082616e-01 6.30976137e-16]
2.1784148785229476e-15


### Úloha pre pokročilých v NumPy

Implementujte [Kabschov algoritmus](https://en.wikipedia.org/wiki/Kabsch_algorithm). A nájdite ním maticu R, ktorou boli vytvorené dáta X a Y z kódu nižšie.

In [ ]:
X = np.random.randint(0, 20, size=(20, 3))

R = np.linalg.qr(np.random.randn(3, 3))[0]
if np.linalg.det(R) < 0:
  R[:, 2] *= -1


Y = (R @ X.T).T + np.random.randn(20, 3) * 0.1

## Dokumentácia NumPy
Na nasledujúcom cvičení si prejdeme základné operácie lineárnej algebry a štatistiky na tenzoroch z NumPy. Ak by ste si chceli pozrieť viacero príkázov a možností manipulácie, tak si môžete pozrieť dokuemntáciu: https://docs.scipy.org/doc/numpy/