<a href="https://colab.research.google.com/github/kocurvik/edu/blob/master/3DV/labs/cv01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1. cvičenie** - Google Colab, Základy NumPy, Základná manipulácia s obrazom v OpenCV

V tomto notebooku si ukážeme ako pracovať v Google Colab a s poliami v NumPy.

## Google Colab

Google Colab (http://colab.research.google.com) je nespoplatnená služba na ktorej je možné spúštať tzv. ipython noteboky. Služba poskytuje k dispozícii aj výpočty na GPU a CPU. Pre využitie tejto služby je nutné mať Google účet. Tieto notebooky môžeme spúšťať aj lokálne pomocou príkazu `jupyter notebook` v zložke kde máme uložené ipynb súbory.

V notebookoch máme dva druhy buniek. Textové, ako napr. tento a kód. Bunky s kódom môžeme spúštať tlačidlom play naľavo od bunky, alebo v prostredí Colab naraz od prvej až po poslednú výberom Runtime -> Run All. Defaultne notebook nemá pripojené GPU, to môžeme zmeniť zavolaním Runtime -> Change runtime type. Bunky majú spoločný scope ale je treba dávať pozor na poradie spúštania jednotlivých buniek. Preto je často vhodné použiť Runtime -> Restart and run all.

V nasledujúcej bunke si môžete otestovať spustenie python kódu.

In [ ]:
a = [5,'Hello']
s = '{} World!'
print(s.format(a[1]))

def najlepsia_funkcia(arg):
  return arg + 5

print(najlepsia_funkcia(8))

Hello World!
13


Keď sme v Google Colab chceli by sme mať prístup k súborom. To je najjednoduchšie pomocou pripojenia Google Drive k našej inštancii. To sa robí následovne:
(V Google Drive si vyrobte zložku Colab, alebo upravte na drive)

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')
root_path = 'gdrive/My Drive/Colab/'

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


Môžeme potom k zložke pristupovať.

In [ ]:
import os
os.listdir(root_path)

['mnist-fc-trained.h5', 'cifar-fc-trained.h5']

Takisto môžeme volať unixové príkazy pomocou výkričníka.

In [ ]:
!pwd
!ls
!mkdir random_dir
!ls
!wget https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png
!ls

/content
gdrive	googlelogo_color_272x92dp.png  random_dir  sample_data
mkdir: cannot create directory ‘random_dir’: File exists
gdrive	googlelogo_color_272x92dp.png  random_dir  sample_data
--2024-02-20 22:38:23--  https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png
Resolving www.google.com (www.google.com)... 108.177.127.106, 108.177.127.104, 108.177.127.103, ...
Connecting to www.google.com (www.google.com)|108.177.127.106|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5969 (5.8K) [image/png]
Saving to: ‘googlelogo_color_272x92dp.png.1’

googlelogo_color_27 100%[===================>]   5.83K  --.-KB/s    in 0s      

2024-02-20 22:38:23 (60.1 MB/s) - ‘googlelogo_color_272x92dp.png.1’ saved [5969/5969]

gdrive	googlelogo_color_272x92dp.png  googlelogo_color_272x92dp.png.1	random_dir  sample_data


Najpohodlnejšia možnosť je použiť inferface naľovo a pozrieť si záložku Files

**<----**

## NumPy

Pri práci budeme veľmi často používať NumPy. Jeho základnou štruktúrou je pole. Polia obecne môžu reprezentovať vektory, matice a tenzory vyšších rádov. Napr. množinu matíc, ktoré majú rovnaké rozmery môžeme reprezentovať ako pole tretieho rádu.

Podľa konvencie sa numpy väčšinou importuje ako np.

Vektor, teda 1-rozmerné pole, vieme vyrobiť z jednuchého listu. Pomocou np.array. Často je dôležité použiť správny dátový typ to urobíme pomocou argumentu dtype. **Vynechanie tejto časti môže viesť na rôzne komplikácie!**

In [ ]:
import numpy as np

a = np.array([3, 2, 3, 4])
print(a)
b = np.array([1,5,7], dtype=np.float32)
print(b)

[3 2 3 4]
[1. 5. 7.]


Maticu vieme vyrobiť z listu listov, ale treba dať pozor aby nám sedeli dĺžky vnútorných listov. Inak sa vytvorí tenzor prvého rádu, ktorý obsahuje listy.

In [ ]:
A = np.array([[1,5,8],[50,60,84]])
print(A)
B = np.array([[7,8],[6,7],[0,9,4]])
print(B)

[[ 1  5  8]
 [50 60 84]]


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

Objekt array má metódu shape, ktorá nám umožňuje zistiť jej tvar (teda dimenzie), metódu dtype ktorá vracia typ vnútorných objektov a metódu astype, ktorá vráti tenzor v podľa špecifikovaného typu.

In [ ]:
print(a.shape)
print(A.shape)
print(A.dtype)
C = A.astype(np.float32)
print(C.dtype)


(4,)
(2, 3)
int64
float32


Numpy má aj funkcie na tvorenie základných matíc. Tieto príkazy sú np.zeros, np.ones a np.empty.

In [ ]:
z = np.zeros([5,10])
print(z)
o = np.ones([3,4,5])
print(o)
e = np.empty([6])
print(e)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
[5.02837521e-310 0.00000000e+000 0.00000000e+000 0.00000000e+000
 0.00000000e+000 0.00000000e+000]


Je možné tvoriť aj náhodné čísla pomocou np.random.random

In [ ]:
r = np.random.random([6,10,3])
print(r)

[[[0.14478643 0.53427788 0.40414145]
  [0.79032232 0.68475832 0.30393307]
  [0.82925597 0.76063917 0.91794753]
  [0.97356368 0.74975149 0.49798395]
  [0.83374146 0.15407754 0.29123402]
  [0.40810307 0.58777082 0.1940629 ]
  [0.8122177  0.52149053 0.90088098]
  [0.25515479 0.88509522 0.00539467]
  [0.08064368 0.14493713 0.68460196]
  [0.95262084 0.22559341 0.77942397]]

 [[0.72495489 0.26666451 0.02674314]
  [0.35784615 0.16937158 0.35810124]
  [0.56213707 0.27505371 0.74090532]
  [0.86355222 0.70131693 0.91913588]
  [0.91479506 0.07380738 0.41580597]
  [0.79677721 0.24891565 0.72421338]
  [0.22293009 0.95169664 0.4928591 ]
  [0.00451619 0.89345336 0.72087757]
  [0.56300535 0.02268214 0.85411629]
  [0.09462268 0.13700071 0.47803374]]

 [[0.88341915 0.86126334 0.78607568]
  [0.1809785  0.07107076 0.88507609]
  [0.37500172 0.70150143 0.12544439]
  [0.39606585 0.1767097  0.75375095]
  [0.95289694 0.36473825 0.76218341]
  [0.04216948 0.13386511 0.17148646]
  [0.46616503 0.50108156 0.4296735

Tieto náhodné čísla použijeme na prácu s indexmi. Indexácia je podobná ako v matlabe, ale platia tu pythonovské konvencie. Indexuje sa viacerými indexmi. Ak sa indexuje menej indexmi, tak sa tie ostatné berú ako :, čo znamená zobartie všetkých prvkov pozdĺž dimenzie.

In [ ]:
print(r[3,4,1])
print(r[:,:,-1])
print(r[:,:,1].shape)
print(r[0:4,5:6,:])
print(r[0:4,5:6,:].shape)

0.008889023626534542
[[0.40414145 0.30393307 0.91794753 0.49798395 0.29123402 0.1940629
  0.90088098 0.00539467 0.68460196 0.77942397]
 [0.02674314 0.35810124 0.74090532 0.91913588 0.41580597 0.72421338
  0.4928591  0.72087757 0.85411629 0.47803374]
 [0.78607568 0.88507609 0.12544439 0.75375095 0.76218341 0.17148646
  0.42967351 0.02679603 0.81150325 0.54081763]
 [0.53377874 0.60396008 0.03725937 0.65049681 0.26926025 0.89206298
  0.94162055 0.46213307 0.26202369 0.03716076]
 [0.33492484 0.11692219 0.63106549 0.03821826 0.12018581 0.73255946
  0.62501294 0.7853719  0.8484383  0.87942515]
 [0.99343041 0.32560641 0.90991454 0.98000997 0.97629298 0.28896009
  0.87507736 0.4658675  0.27187979 0.25763133]]
(6, 10)
[[[0.40810307 0.58777082 0.1940629 ]]

 [[0.79677721 0.24891565 0.72421338]]

 [[0.04216948 0.13386511 0.17148646]]

 [[0.45824987 0.93677238 0.89206298]]]
(4, 1, 3)


Indexovať môžeme aj s preskakovaním jednotlivých prvkov, tzv. slicing. To sa robí pomocou ďalšej dvojbodky. Formát je potom \[začiatok:koniec:skok\]. Ak niečo z toho vynecháme, tak žačiatok bude defaultne 0, koniec -1 a skok 1.

In [ ]:
p = np.arange(25)
print(p)
print(p[4:16:2])
print(p[2:-4:6])
print(p[:10:])
print(p[::3])
print(p[1::6])
print(p[-6:])
print(r[1::2,0::3,:])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[ 4  6  8 10 12 14]
[ 2  8 14 20]
[0 1 2 3 4 5 6 7 8 9]
[ 0  3  6  9 12 15 18 21 24]
[ 1  7 13 19]
[19 20 21 22 23 24]
[[[0.72495489 0.26666451 0.02674314]
  [0.86355222 0.70131693 0.91913588]
  [0.22293009 0.95169664 0.4928591 ]
  [0.09462268 0.13700071 0.47803374]]

 [[0.61055413 0.49660675 0.53377874]
  [0.60404269 0.60697686 0.65049681]
  [0.13746533 0.52804016 0.94162055]
  [0.267996   0.50015077 0.03716076]]

 [[0.19171468 0.82362729 0.99343041]
  [0.04431505 0.26243773 0.98000997]
  [0.47796017 0.53895132 0.87507736]
  [0.634953   0.56083893 0.25763133]]]


Niekedy potrebujeme vytvoriť tzv. singleton dimenziu. To znamená že zvýšime rád zvoleného tenzoru o jedna pričom novovzniknutá osa (axis) bude mať dimenziu jedna. Toto je užitočné najmä ak potrebujeme používať broadcasting pri rôznych operáciách.

In [ ]:
print(r[None,:,:,:].shape)
print(r[None].shape)
print(r[np.newaxis,:,:,:].shape)
print(r[:,:,:,np.newaxis].shape)
print(r[np.newaxis,:,0,:].shape)

(1, 6, 10, 3)
(1, 6, 10, 3)
(1, 6, 10, 3)
(6, 10, 3, 1)
(1, 6, 3)


Teraz môžeme vidieť v akcii aj broadcasting.

In [ ]:
r += 10
print(r)
r[0,:,:] = np.random.random([10,3])
print(r.shape)
r[0] = np.random.random([10,3])
print(r.shape)
r[0] = np.zeros([10,1])
print(r.shape)
r/=500
print(r)

[[[10.14478643 10.53427788 10.40414145]
  [10.79032232 10.68475832 10.30393307]
  [10.82925597 10.76063917 10.91794753]
  [10.97356368 10.74975149 10.49798395]
  [10.83374146 10.15407754 10.29123402]
  [10.40810307 10.58777082 10.1940629 ]
  [10.8122177  10.52149053 10.90088098]
  [10.25515479 10.88509522 10.00539467]
  [10.08064368 10.14493713 10.68460196]
  [10.95262084 10.22559341 10.77942397]]

 [[10.72495489 10.26666451 10.02674314]
  [10.35784615 10.16937158 10.35810124]
  [10.56213707 10.27505371 10.74090532]
  [10.86355222 10.70131693 10.91913588]
  [10.91479506 10.07380738 10.41580597]
  [10.79677721 10.24891565 10.72421338]
  [10.22293009 10.95169664 10.4928591 ]
  [10.00451619 10.89345336 10.72087757]
  [10.56300535 10.02268214 10.85411629]
  [10.09462268 10.13700071 10.47803374]]

 [[10.88341915 10.86126334 10.78607568]
  [10.1809785  10.07107076 10.88507609]
  [10.37500172 10.70150143 10.12544439]
  [10.39606585 10.1767097  10.75375095]
  [10.95289694 10.36473825 10.762183

Je možné polia pretvarovať pomocou np.reshape(arr, shape)

In [ ]:
q = np.reshape(r, [6,30])
print(q.shape)

(6, 30)


Polia môžeme spájať. Jeden spôsob je pomocou np.concatenate([arr1, arr2, ...], axis = i) t=a spojí arr1, arr2 atď. vedľa seba pozdĺž osy i.

In [ ]:
a = np.ones([3,4])
b = np.zeros([6,4])
c = np.concatenate([a,b], axis = 0)
print(c)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Iný spôsob je použitie np.stack([arr1, arr2, ...], axis = i) narozdiel od cocatenate sa pri tomto príkaze vytvorí nová dimenzia poďľa hodnoty i. Existujú aj príkazy column_stack a row_stack.

In [ ]:
a = np.ones([6,4,3])
b = np.zeros([6,4,3])
d = np.stack([a,b], axis = 0)
print(d.shape)
f = np.stack([a,b], axis = -1)
print(f.shape)
g = np.stack([a,b], axis = 1)
print(g.shape)

(2, 6, 4, 3)
(6, 4, 3, 2)
(6, 2, 4, 3)


Indexovať môžeme aj pomocou podmienok.

In [ ]:
r = np.random.random([5,5])
print(r)
r[r < 0.5] = -500
print(r)

[[0.32920764 0.50547436 0.28576236 0.63010107 0.25109483]
 [0.83579578 0.34312103 0.68595921 0.41316596 0.80955637]
 [0.81158645 0.29224975 0.31377868 0.75321982 0.5931154 ]
 [0.981677   0.47415953 0.68808376 0.57652848 0.13928623]
 [0.62490618 0.67962538 0.159209   0.37766715 0.43192625]]
[[-500.            0.50547436 -500.            0.63010107 -500.        ]
 [   0.83579578 -500.            0.68595921 -500.            0.80955637]
 [   0.81158645 -500.         -500.            0.75321982    0.5931154 ]
 [   0.981677   -500.            0.68808376    0.57652848 -500.        ]
 [   0.62490618    0.67962538 -500.         -500.         -500.        ]]


Podmienky môžeme použiť aj np.where(cond, a1, a2), ktorá vráti pole ktoré ma na miestach kde je cond splnená hodnoty z a1 a inde hodnoty z a2. Použijeme tu príkaz np.arange(i), ktorý vráti pole podobne ako range z pythonu.

In [ ]:
a = np.arange(10)
print(a)
b = np.where(a < 5, a, a**2)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4 25 36 49 64 81]


### Úloha - Chessboard
Vytvorte funkciu chessboard(rows, cols), ktorá vráti numpy pole s riadkami rows a stĺpcami cols ktorá bude mať hodnoty 0 a 1 na takých miestach ako sú farby na šachovnici. Môžete použiť slicing, podmienky (zíde sa vám np.mgrid), alebo opakovanie matíc (np.tile)

In [ ]:
def chessboard(rows, cols):
  ...

In [ ]:
print(chessboard(8,8))
print(chessboard(5,12))

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]
[[0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]]


### Úloha - Indexovanie

Vygenerujte náhodnú maticu s rozmermi 10 x 5 z rovnomerného rozdelenia. Následne zmente všetky prvky väčšie ako 0.8 na 1. Následne zmenťe všetky prvky menšie ako 0.3 na polovicu hodnoty na rovnakom riadku ale, vo vedľajšom stĺpci naľavo. Ak sú takéto hodnoty v prvom stĺpci, tak ich zmeňte na 0. Operáciu urobte tak, ako keby ste robili všetky zmeny naraz. V kóde to však nemusí byť jedna operácia. Budete potrebovať logickú indexáciu a v druhom prípade aj np.where. Nepoužite for cyklus.

In [ ]:
...

[[0.5886539  0.11017985 0.33564695 0.24176277 0.28556255]
 [0.36332772 0.06447582 0.0120402  0.63002809 0.29573919]
 [0.52436167 0.75365233 0.97480034 0.9334547  0.61597547]
 [0.30279468 0.91809083 0.07937651 0.76628124 0.46777759]
 [0.01410127 0.58362368 0.42294372 0.33268421 0.05290472]
 [0.64485157 0.61684957 0.14032802 0.35384101 0.65628373]
 [0.08051455 0.4457815  0.85087719 0.9692016  0.00808913]
 [0.43103199 0.42465607 0.16832863 0.2951669  0.52380026]
 [0.07637356 0.1347941  0.40210387 0.19447398 0.82403839]
 [0.94769323 0.6116006  0.11546063 0.57721486 0.57746055]]
[[0.5886539  0.11017985 0.33564695 0.24176277 0.28556255]
 [0.36332772 0.06447582 0.0120402  0.63002809 0.29573919]
 [0.52436167 0.75365233 1.         1.         0.61597547]
 [0.30279468 1.         0.07937651 0.76628124 0.46777759]
 [0.01410127 0.58362368 0.42294372 0.33268421 0.05290472]
 [0.64485157 0.61684957 0.14032802 0.35384101 0.65628373]
 [0.08051455 0.4457815  1.         1.         0.00808913]
 [0.43103199 

## Matematické operácie

Na polia môžeme aplikovať tiež matematické operácie.

In [ ]:
r = np.random.rand(10, 2)

In [ ]:
print(np.sin(r))
print(np.cos(r))
print(np.arccos(r))
print(np.exp(r))
print(r ** 2)

[[0.20108657 0.23071489]
 [0.27898168 0.58398296]
 [0.08260066 0.80804065]
 [0.18875099 0.27800424]
 [0.05749393 0.20637746]
 [0.47216615 0.0346453 ]
 [0.83291911 0.16107856]
 [0.32257109 0.76622003]
 [0.17296259 0.71428879]
 [0.37661214 0.75645625]]
[[0.97957348 0.9730214 ]
 [0.96029642 0.81176591]
 [0.99658273 0.58912674]
 [0.98202498 0.96057985]
 [0.99834586 0.97847245]
 [0.88150957 0.99939967]
 [0.55339476 0.98694159]
 [0.94654524 0.64257829]
 [0.98492839 0.69985108]
 [0.92637104 0.65404429]]
[[1.36691987 1.33582785]
 [1.28415361 0.89742289]
 [1.48800691 0.3457586 ]
 [1.3797461  1.28521443]
 [1.5132389  1.36139814]
 [1.05670196 1.53613716]
 [0.17708238 1.40829874]
 [1.23614007 0.50960383]
 [1.39607186 0.65078688]
 [1.17435684 0.53967097]]
[[1.2244197  1.26214459]
 [1.32675157 1.86568192]
 [1.08621033 2.56207794]
 [1.20911673 1.32540202]
 [1.05921244 1.23105468]
 [1.63516952 1.03525961]
 [2.67610357 1.17560557]
 [1.38880619 2.39393353]
 [1.18986137 2.21578633]
 [1.47128539 2.3581509

## Súhrnné operácie
Na numpy poliach je možné robiť aj rôzne operácie. Je napríklad možné sčítať pole pomocou príkazu np.sum. Podobne fungujú aj príkazy np.min (mininum), np.max(maximum), np.mean (priemer), np.median (medián), np.var (variácia) a np.std (štandardná odchýlka).



In [ ]:
a = np.random.rand(4, 3)
print(a)
print(np.mean(a))
print(np.median(a))
print(np.sum(a))
print(np.max(a))
print(np.std(a))

[[0.29355358 0.09707809 0.46212523]
 [0.25228151 0.80615269 0.44884943]
 [0.89777785 0.8265036  0.47266966]
 [0.43243425 0.99026449 0.3745671 ]]
0.5295214567887344
0.4554873298781432
6.354257481464813
0.9902644911158512
0.27078425790958366


## Kľučové slovo axis

Často chceme operáciu napr. sčítanie realizovať len po nejakej dimenzii. V takom prípade je vhodné využiť kľučové slovo axis. To nám umožní sčítavať po konkrétnej dimenzii. Je možné použiť aj tuple dimenzii po ktorých je možné sčítavať. Veľa numpy príkazov má tento keyword k dispozícii a je vhodné sa ho dobre naučiť používať.


In [ ]:
print(a)
print(np.sum(a, axis=0))
print(np.sum(a, axis=0).shape)
print(np.sum(a, axis=1))
print(np.sum(a, axis=1).shape)

b = np.random.rand(4,3,16,16)
print(np.sum(b, axis=(1,2,3)))
print(np.sum(b, axis=(1,2,3)).shape)

[[0.29355358 0.09707809 0.46212523]
 [0.25228151 0.80615269 0.44884943]
 [0.89777785 0.8265036  0.47266966]
 [0.43243425 0.99026449 0.3745671 ]]
[1.87604719 2.71999887 1.75821142]
(3,)
[0.8527569  1.50728363 2.19695111 1.79726584]
(4,)
[377.54030722 378.55074849 384.25422276 402.17363101]
(4,)


Pre minimum a maximum existujú ešte dve funkcie (np.minimum a np.maximum), ktoré porovnajú dve polia.

In [ ]:
b = ((np.arange(12) - 7) * 2).reshape(4,3)
print(b)
print(np.maximum(a, b))

[[-14 -12 -10]
 [ -8  -6  -4]
 [ -2   0   2]
 [  4   6   8]]
[[0.29355358 0.09707809 0.46212523]
 [0.25228151 0.80615269 0.44884943]
 [0.89777785 0.8265036  2.        ]
 [4.         6.         8.        ]]


### Úloha - Euklidovksá metrika

Implementujte funkciu euclidian_distance_single(x, y), ktorá na vstupe príjme dva vektory x a y, ktoré sú oba z $\mathbb{R}^n$ a vypočíta:

$$\rho_e(\vec{x}, \vec{y}) = \sqrt{\sum_{i=1}^{n} \left(x_i - y_i\right)^2}$$

In [ ]:
def euclidian_distance_single(x, y):
  ...

Kód môžeme otestovať pomocou funkcie np.linalg.norm, ktorá ráta to isté:

In [ ]:
for i in range(10):
  n = np.random.randint(100)
  a = np.random.rand(n)
  b = np.random.rand(n)

  d = euclidian_distance_single(a, b)
  d_gt = np.linalg.norm(a - b)
  if np.abs(d_gt - d) < 1e-8:
    print("Pass!")
  else:
    print("Fail")

Pass!
Pass!
Pass!
Pass!
Pass!
Pass!
Pass!
Pass!
Pass!
Pass!


### Úloha - Euklidovská metrika - vektorizovane

Teraz vytvoríme novú funkciu euclidian distance, ktorá bude fungovať tak, že x bude vektor $\mathbb{R}^n$ a y bude matica $m \times n$, ktorej každý riadok je vektor z $\mathbb{R}^n$. Funkcia potom vráti vektor dĺžky $m$, ktorý bude obsahovať metriky medzi x a jednotlivými vektormi z y.

In [ ]:
def euclidian_distance(x, y):
  ...

Kód otestujeme:

In [ ]:
for i in range(10):
  n = np.random.randint(100)
  a = np.random.rand(n)
  b = np.random.rand(30, n)

  d = euclidian_distance(a, b)

  for i in [4,9,13,24]:
    if np.abs(np.linalg.norm(a - b[i]) - d[i]) < 1e-8:
      print("Pass!")
    else:
      print("Fail!")

Pass!
Pass!
Pass!
Pass!
Pass!
Pass!
Pass!
Pass!
Pass!
Pass!
Pass!
Pass!
Pass!
Pass!
Pass!
Pass!
Pass!
Pass!
Pass!
Pass!
Pass!
Pass!
Pass!
Pass!
Pass!
Pass!
Pass!
Pass!
Pass!
Pass!
Pass!
Pass!
Pass!
Pass!
Pass!
Pass!
Pass!
Pass!
Pass!
Pass!


## Násobenie

Polia môžeme tiež násobiť. Môžeme použiť buď operátor `*`, ktorý realizuje násobenie po elementoch, alebo operátor `@`, ktorý realizuje maticové násobenie. V prípade `@` sa vektor vždy považuje za stĺpcový, alebo riadkový podľa toho čo sa hodí. Tiež je na násobenie možné použiť `np.dot`. Matice môžeme tiež transponovať metódou `.T`

In [ ]:
x = np.array([1, 2, 3])
y = np.array([8, 0, 7])

A = np.arange(9).reshape(3, 3)
B = np.random.rand(4, 3)
C = np.random.rand(3, 3)

print(x @ y)
print(x * y)

print(20 * '*')

print(A @ x)
print(y @ A)
print(x @ C)
print(x @ A @ y)

print(20 * '*')

print(A * C)
print(A @ C)
print(B @ A)

print(20 * '*')

#pri nasobeni po prvkoch moze dojst k broadcastingu
print(A * x)

print(20 * '*')

#tieto nebudu fungovat
print(x @ B)
print(A @ B)

29
[ 8  0 21]
********************
[ 8 26 44]
[42 57 72]
[1.30698358 4.49904052 2.37701887]
444
********************
[[0.         0.89703746 1.55558661]
 [0.05335647 2.81490223 1.53679063]
 [1.14954946 5.1206212  2.62535817]]
[[ 0.40096864  2.16676019  0.96369767]
 [ 3.11901345  9.16360119  5.20366127]
 [ 5.83705826 16.1604422   9.44362488]]
[[5.00367511 6.41134441 7.81901372]
 [5.64860452 7.73219168 9.81577884]
 [4.738323   6.04476243 7.35120186]
 [2.24522887 3.21883778 4.1924467 ]]
********************
[[ 0  2  6]
 [ 3  8 15]
 [ 6 14 24]]
********************


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 3)

### Úloha - Eulerové uhly

Implementujte funkciu euler_to_rotmat(alpha, beta, gamma), ktorá na vstupe dostane tri uhly $\alpha, \beta, \gamma$ v stupňoch a vráti rotačnú maticu $R$ ako kompozíciu troch rotácií.

$$ R = R_z(\gamma) \, R_y(\beta) \, R_x(\alpha) =
  \begin{pmatrix}
    \cos \gamma & -\sin \gamma & 0 \\
    \sin \gamma &  \cos \gamma & 0 \\
     0          &   0          & 1 \\
  \end{pmatrix}\begin{pmatrix}
    \cos \beta & 0 & \sin \beta \\
     0         & 1 &  0 \\
   -\sin \beta & 0 & \cos \beta \\
  \end{pmatrix}\begin{pmatrix}
    1 &  0          &   0 \\
    0 & \cos \alpha & -\sin \alpha \\
    0 & \sin \alpha &  \cos \alpha \\
  \end{pmatrix} $$

Pre implementáciu použite funkcie `np.cos` a `np.sin` a maticové násobenie. Kód si môžete dole otestovať. Nezabudnite na rozdiel medzi radiánmi a stupňami.

Implementujte aj inverznú funkciu `rotmat_to_euler`, ktorá na vstupe dostane maticu $3 \times 3$ a vráti tri Eulerove uhly v stupňoch. Môžete použiť nasledujúce vzorce:

$$\gamma = \text{atan2}(r_{21}, r_{11}),
  \beta = \text{atan2}\left(-r_{31}, \sqrt{r_{32}^2 + r_{33}^2}\right),
  \alpha = \text{atan2}(r_{32}, r_{33})
$$

Požite funkciu `np.arctan2`.



In [ ]:
def euler_to_rotmat(alpha, beta, gamma):
  ...

def rotmat_to_euler(R):
  ...

In [ ]:
import scipy

print("Testing Euler -> rotmat")

for i in range(10):
  alpha, beta, gamma = 360 * np.random.rand(3) - 180
  R_test = scipy.spatial.transform.Rotation.from_euler('xyz', (alpha, beta, gamma), degrees=True).as_matrix()
  R_impl = euler_to_rotmat(alpha, beta, gamma)
  if np.linalg.norm(R_test - R_impl) < 1e-8:
    print("Pass")
  else:
    print("Fail")

print("Testing rotmat -> Euler")
for i in range(10):
  euler_angles = 360 * np.random.rand(3) - 180
  R_test = scipy.spatial.transform.Rotation.from_euler('xyz', euler_angles, degrees=True).as_matrix()
  euler_angles_impl = np.array(rotmat_to_euler(R_test))
  if np.linalg.norm(euler_angles - euler_angles_impl) < 1e-8:
    print("Pass")
  else:
    print("Fail")

Testing Euler -> rotmat
Pass
Pass
Pass
Pass
Pass
Pass
Pass
Pass
Pass
Pass
Testing rotmat -> Euler
Pass
Pass
Fail
Pass
Pass
Pass
Pass
Pass
Fail
Pass


## Dokumentácia NumPy
Na nasledujúcom cvičení si prejdeme základné operácie lineárnej algebry a štatistiky na tenzoroch z NumPy. Ak by ste si chceli pozrieť viacero príkázov a možností manipulácie, tak si môžete pozrieť dokuemntáciu: https://docs.scipy.org/doc/numpy/