<a href="https://colab.research.google.com/github/kocurvik/edu/blob/master/cvicenia/notebooky/cv04_en_solution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **4. lab** - Google Colab, NumPy and Pandas Basics, Feature Entropy

In this notebook we will cover the basics of working in the Google Colab environment, NumPy and basic image manipulation in OpenCV.

## Google Colab

Google Colab (http://colab.research.google.com) is a free service which allows the users to run ipython notebooks in the cloud. The service also allows the users to leverage a free GPU. A Google account is necessary to use this service. The notebooks can also be downloaded and run locally using the jupyter notebook in the directory where the notebooks are saved (provided you have jupyter installed).

There are two types of cells in these notbooks. The first type is a text cell such as this one. The other type of a cell is code cell. The cells with code can be run with the play button to the left of the cell. All of the cells can also be run by clicking choosing Runtime -> Run All in the menu at the top of this page. The cells share a scope so it is necessary to be mindful of the order in which the cells run. If you need to restart the notebook you can look into the Runtime tab in the options on top of the page.

You can try running a simple python code in the following cell.

In [ ]:
a = [5,'Hello']
s = '{} World!'
print(s.format(a[1]))

def najlepsia_funkcia(arg):
  return arg + 5

print(najlepsia_funkcia(8))

Hello World!
13


Saving and using files that are stored permanently can be done in different ways, but the easiest option is to connecting Google Drive to our notebook instance. This is done in a following way:
(Note: this assumes that you have created a directory named Colab in your Google Drive)

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')
root_path = 'gdrive/My Drive/Colab/'

Mounted at /content/gdrive


You can then access the folder (if it exists).

In [ ]:
import os
os.listdir(root_path)

['mnist-fc-trained.h5', 'cifar-fc-trained.h5']

You can also use the standard unix commands by preceeding them with an exclamation point.

In [ ]:
!pwd
!ls
!mkdir random_dir
!ls
!wget https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png
!ls

/content
gdrive	sample_data
gdrive	random_dir  sample_data
--2022-03-13 23:43:05--  https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png
Resolving www.google.com (www.google.com)... 108.177.127.147, 108.177.127.103, 108.177.127.106, ...
Connecting to www.google.com (www.google.com)|108.177.127.147|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5969 (5.8K) [image/png]
Saving to: ‘googlelogo_color_272x92dp.png’

googlelogo_color_27 100%[===================>]   5.83K  --.-KB/s    in 0s      

2022-03-13 23:43:06 (64.0 MB/s) - ‘googlelogo_color_272x92dp.png’ saved [5969/5969]

gdrive	googlelogo_color_272x92dp.png  random_dir  sample_data


This is not always necessary as you can access the instance file structure in the panel on the left.

**<----**

## NumPy
A tensor is a base data structure we will use when dealing with neural networks. Tensor is a generalization of vectors and matrices. Vectors from $\mathbb{R}^n$ are first order (rank) tensors and matrices are second order (rank) tensors. A third order (rank) tensor can be additionally indexed with one more index. Sometimes the order of tensor is also called its rank. Strictly speaking tensor dimension and order are two different concepts. For example, we can have a third order tensor with dimension $ 20 \times 24 \times 6$. However, in many texts authors interchange tensor order (rank) with dimension. This is sometimes confusing, but usually the meaning is evident from context.

To conform to standards we import numpy as np. A vector (e.g. first order tensor) can be created from a simple list using the np.array constructor. It might be important to initialize the array with a specific data type which can be done by using the dtype keyword in the constructor. **Not specifying the dtype can cause various complications later in the code.**


In [ ]:
import numpy as np

a = np.array([3, 2, 3, 4])
print(a)
b = np.array([1,5,7], dtype=np.float32)
print(b)

[3 2 3 4]
[1. 5. 7.]


A matrix can be created from a list of lists, but it is necessary for the lengths of the inner lists to be consitent. If they are not consistent we will obtain a vector of lists instead of matrix of values.

In [ ]:
A = np.array([[1,5,8],[50,60,84]])
print(A)
B = np.array([[7,8],[6,7],[0,9,4]])
print(B)

[[ 1  5  8]
 [50 60 84]]
[list([7, 8]) list([6, 7]) list([0, 9, 4])]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  This is separate from the ipykernel package so we can avoid doing imports until


The array object has a shape method which tells us its shape (dimensions) and method dtype which returns the data type of the values in the tensor. It also has a method astype which returns an array with the specified type.

In [ ]:
print(a.shape)
print(A.shape)
print(A.dtype)
C = A.astype(np.float32)
print(C.dtype)


(4,)
(2, 3)
int64
float32


Numpy has a few functions to generate basic tensors. The most commnly used onse are: np.zeros, np.ones and np.empty.

In [ ]:
z = np.zeros([5,10])
print(z)
o = np.ones([3,4,5])
print(o)
e = np.empty([6])
print(e)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
[4.68492522e-310 9.52256738e-292 4.52191083e-302 9.47918153e+189
 4.25932742e+180 1.81786184e+185]


It is also possible the create tensors with random numbers by using np.random.random.

In [ ]:
r = np.random.random([6,10,3])
print(r)

[[[0.0053455  0.59692604 0.44203988]
  [0.40289258 0.07656003 0.32049852]
  [0.97075092 0.74815306 0.44935753]
  [0.39184387 0.20246279 0.38757038]
  [0.39962678 0.32409525 0.7927391 ]
  [0.0898963  0.92463692 0.49345864]
  [0.59253072 0.97457087 0.40127513]
  [0.53042302 0.56916547 0.15112752]
  [0.70102921 0.32585247 0.19856047]
  [0.50909383 0.74902486 0.65890903]]

 [[0.3116623  0.81468682 0.97577625]
  [0.88090974 0.24675129 0.77555195]
  [0.55056838 0.88478178 0.21951067]
  [0.85507684 0.91495289 0.81289874]
  [0.64081369 0.11813502 0.47497979]
  [0.71925473 0.35455605 0.90652253]
  [0.31438884 0.08824486 0.29964114]
  [0.11894364 0.37886605 0.04230567]
  [0.53212403 0.37444282 0.6657364 ]
  [0.8384853  0.50758163 0.4315342 ]]

 [[0.24462593 0.64757326 0.59474227]
  [0.80454138 0.15894817 0.94622422]
  [0.58525207 0.24103985 0.3675816 ]
  [0.05530789 0.7568578  0.76520013]
  [0.93902097 0.39384954 0.4752404 ]
  [0.32507473 0.45539338 0.50522788]
  [0.59923845 0.87557235 0.7346001

We can now use these random arrays to work with indices. Indexing is similar to Matlab, but the python conventions are applied. We can use multiple indices (based on tensor order). If we omit one of the indices it is implicitly used as :, which means that all of the elements along that dimesnsions are used.

In [ ]:
print(r[3,4,1])
print(r[:,:,-1])
print(r[:,:,1].shape)
print(r[0:4,5:6,:])
print(r[0:4,5:6,:].shape)

0.3523754062419985
[[0.44203988 0.32049852 0.44935753 0.38757038 0.7927391  0.49345864
  0.40127513 0.15112752 0.19856047 0.65890903]
 [0.97577625 0.77555195 0.21951067 0.81289874 0.47497979 0.90652253
  0.29964114 0.04230567 0.6657364  0.4315342 ]
 [0.59474227 0.94622422 0.3675816  0.76520013 0.4752404  0.50522788
  0.73460017 0.66619272 0.03221085 0.1875413 ]
 [0.63900055 0.43112974 0.84232816 0.17327822 0.39872609 0.13097156
  0.93583746 0.67524874 0.4756662  0.05818639]
 [0.66720776 0.49235526 0.19016745 0.8010884  0.66906467 0.79796016
  0.55709063 0.8071917  0.12760769 0.07505624]
 [0.12667549 0.44850115 0.08097574 0.12406906 0.39798522 0.7729316
  0.65932398 0.35964269 0.59109751 0.84614044]]
(6, 10)
[[[0.0898963  0.92463692 0.49345864]]

 [[0.71925473 0.35455605 0.90652253]]

 [[0.32507473 0.45539338 0.50522788]]

 [[0.96736194 0.91567991 0.13097156]]]
(4, 1, 3)


We can also use steps when indexing this is also called slicing. That can be done by another colon. The format is then [start:stop:step]. If any of that is left empty the start is implicitly assumed to be 0, the end -1 and step 1.

In [ ]:
p = np.arange(25)
print(p)
print(p[4:16:2])
print(p[2:-4:6])
print(p[:10:])
print(p[::3])
print(p[1::6])
print(p[-6:])
print(r[1::2,0::3,:])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[ 4  6  8 10 12 14]
[ 2  8 14 20]
[0 1 2 3 4 5 6 7 8 9]
[ 0  3  6  9 12 15 18 21 24]
[ 1  7 13 19]
[19 20 21 22 23 24]
[[[0.3116623  0.81468682 0.97577625]
  [0.85507684 0.91495289 0.81289874]
  [0.31438884 0.08824486 0.29964114]
  [0.8384853  0.50758163 0.4315342 ]]

 [[0.11582477 0.49257783 0.63900055]
  [0.80223493 0.40026651 0.17327822]
  [0.72632083 0.80388226 0.93583746]
  [0.55208882 0.60917064 0.05818639]]

 [[0.68906021 0.02042693 0.12667549]
  [0.79848067 0.86122212 0.12406906]
  [0.34000966 0.64884004 0.65932398]
  [0.69164509 0.09833494 0.84614044]]]


We will often need to create a so-called singleton dimension. This cane be done by adding a None index, or in a more python way by using np.newaxis.

In [ ]:
print(r[None,:,:,:].shape)
print(r[None].shape)
print(r[np.newaxis,:,:,:].shape)
print(r[:,:,:,np.newaxis].shape)
print(r[np.newaxis,:,0,:].shape)

(1, 6, 10, 3)
(1, 6, 10, 3)
(1, 6, 10, 3)
(6, 10, 3, 1)
(1, 6, 3)


Similar to Matlab broadcasting is done implicitly (though different rules are applied in Matlab).

In [ ]:
r += 10
print(r)
r[0,:,:] = np.random.random([10,3])
print(r.shape)
r[0] = np.random.random([10,3])
print(r.shape)
r[0] = np.zeros([10,1])
print(r.shape)
r/=500
print(r)

[[[10.0053455  10.59692604 10.44203988]
  [10.40289258 10.07656003 10.32049852]
  [10.97075092 10.74815306 10.44935753]
  [10.39184387 10.20246279 10.38757038]
  [10.39962678 10.32409525 10.7927391 ]
  [10.0898963  10.92463692 10.49345864]
  [10.59253072 10.97457087 10.40127513]
  [10.53042302 10.56916547 10.15112752]
  [10.70102921 10.32585247 10.19856047]
  [10.50909383 10.74902486 10.65890903]]

 [[10.3116623  10.81468682 10.97577625]
  [10.88090974 10.24675129 10.77555195]
  [10.55056838 10.88478178 10.21951067]
  [10.85507684 10.91495289 10.81289874]
  [10.64081369 10.11813502 10.47497979]
  [10.71925473 10.35455605 10.90652253]
  [10.31438884 10.08824486 10.29964114]
  [10.11894364 10.37886605 10.04230567]
  [10.53212403 10.37444282 10.6657364 ]
  [10.8384853  10.50758163 10.4315342 ]]

 [[10.24462593 10.64757326 10.59474227]
  [10.80454138 10.15894817 10.94622422]
  [10.58525207 10.24103985 10.3675816 ]
  [10.05530789 10.7568578  10.76520013]
  [10.93902097 10.39384954 10.475240

An array can be reshaped using np.reshape

In [ ]:
q = np.reshape(r, [6,30])
print(q.shape)

(6, 30)


Arrays can be joined. One way is to use np.concatenate([arr1, arr2, ...], axis = i) which connects the arrays arr1 and arr2 through a given axis i. Note that is usually better (for code comprehension) to explicitly use the keyword axis even if it is redundant.

In [ ]:
a = np.ones([3,4])
b = np.zeros([6,4])
c = np.concatenate([a,b], axis = 0)
print(c)                   

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


A different option is to use np.stack([arr1, arr2, ...], axis= i). The difference is that this creates increases the tensor order by one.

In [ ]:
a = np.ones([6,4,3])
b = np.zeros([6,4,3])
d = np.stack([a,b], axis = 0)
print(d.shape)
f = np.stack([a,b], axis = -1)
print(f.shape)
g = np.stack([a,b], axis = 1)
print(g.shape)

(2, 6, 4, 3)
(6, 4, 3, 2)
(6, 2, 4, 3)


We can also index using conditions.

In [ ]:
r = np.random.random([5,5])
print(r)
r[r < 0.5] = -500
print(r)

[[0.91083983 0.32744777 0.36150645 0.17323621 0.19032092]
 [0.42292176 0.61094934 0.5179403  0.16642973 0.83201909]
 [0.57492386 0.77105706 0.40896487 0.60120157 0.36289812]
 [0.45790866 0.61296264 0.2929082  0.67012674 0.3813194 ]
 [0.67516178 0.30934909 0.45586873 0.36481768 0.36001682]]
[[   0.91083983 -500.         -500.         -500.         -500.        ]
 [-500.            0.61094934    0.5179403  -500.            0.83201909]
 [   0.57492386    0.77105706 -500.            0.60120157 -500.        ]
 [-500.            0.61296264 -500.            0.67012674 -500.        ]
 [   0.67516178 -500.         -500.         -500.         -500.        ]]


The conditions can also be using in np.whare(cond, a1, a2), which returns an array which contans elemnts from a1 where the condition is true and elements from a2 where condition is false. We can also use np.arange(i) which is equivalent to range(i) from python.

In [ ]:
a = np.arange(10)
print(a)
b = np.where(a < 5, a, a**2)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4 25 36 49 64 81]


### Exercise 1
Create a funciton chessboard(rows, cols) which returns a numpy array with dimensions rows x cols. The array will contain 1 in spots where a chessboard tile would be white and 0 where a chessboard tile would be black.

The simplest way is to use slicing. If you feel adventurous you can check the NumPy documentation and use conditions with np.mgrid or repetition and np.tile.

In [ ]:
def chessboard(rows, cols):
  c = np.zeros([rows, cols])
  c[::2, 1::2] = 1
  c[1::2, 0::2] = 1
  return c

In [ ]:
print(chessboard(8,8))
print(chessboard(5,12))

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]
[[0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]]


### NumPy Documentation
We will go through some basic linear algebra and statistics operations with NumPy during the next lab. 

If you are curious you can check out the documentation of NumPy: https://docs.scipy.org/doc/numpy/

## Introduction to Pandas
We will use the pandas library to store our data. If we only used numerical features we would be fine with just NumPy, but this is usually not sufficient for categorical data or more complex structures. More info on Pandas data structures can be found in [this user guide](https://pandas.pydata.org/pandas-docs/stable/user_guide/dsintro.html#dsintro)

In [ ]:
import pandas as pd
import numpy as np

### Series

One of the basic datatypes is Series. It is essentially a more sophisticated 1-d array of data, which can include named indices.

In [ ]:
s = pd.Series(np.random.randn(5))
print(s)

s = pd.Series(np.random.randn(5), index=["a", "b", "c", "d", "e"])
print(s)

d = {"a": 0.0, "b": 1.0, "c": 2.0}
print(pd.Series(d))
print(pd.Series(d, index=["b", "c", "d", "a"]))

0   -0.718177
1   -2.486077
2   -1.143047
3   -0.345007
4   -2.068682
dtype: float64
a   -1.102454
b   -0.081492
c    0.083218
d    1.481593
e   -0.360535
dtype: float64
a    0.0
b    1.0
c    2.0
dtype: float64
b    1.0
c    2.0
d    NaN
a    0.0
dtype: float64


In many cases Series can be used in place of standard NumPy array.

In [ ]:
print(s.dtype)
print(s.shape)
print(s[0])
print(s[:3])
print(np.sum(s))
print(np.exp(s))

float64
(5,)
-1.1024538045100478
a   -1.102454
b   -0.081492
c    0.083218
dtype: float64
0.020330737488355344
a    0.332055
b    0.921740
c    1.086778
d    4.399951
e    0.697303
dtype: float64


We can convert Series to a NumPy array.

In [ ]:
print(s.to_numpy())

[-1.1024538  -0.08149177  0.08321767  1.48159335 -0.36053471]


We can also perform indexing and standard operations on Series.

In [ ]:
print(2.5 * s + s)
print(s[s > s.median()])
print(s[[4, 3, 1]])

a   -3.858588
b   -0.285221
c    0.291262
d    5.185577
e   -1.261871
dtype: float64
c    0.083218
d    1.481593
dtype: float64
e   -0.360535
d    1.481593
b   -0.081492
dtype: float64


But beware! Operations rely on the defined indexes! This is different from NumPy.

In [ ]:
print(s[1:] + s[:-1])
n = s.to_numpy()
print(n[1:] + n[:-1])

a         NaN
b   -0.162984
c    0.166435
d    2.963187
e         NaN
dtype: float64
[-1.18394558  0.0017259   1.56481102  1.12105864]


A Series also behaves as a dict!

In [ ]:
print(s["a"])
s["c"] = 0.2
print(s)

-1.1024538045100478
a   -1.102454
b   -0.081492
c    0.200000
d    1.481593
e   -0.360535
dtype: float64


### DataFrames

DataFrame is a 2-d structure of data. We will mostly use this structure!

It can be constructed from:

* Dict of 1D ndarrays, lists, dicts, or Series
* 2-D numpy.ndarray
* Structured or record ndarray
* A Series
* Another DataFrame

In [ ]:
d = {
    "one": pd.Series([1.0, 2.0, 3.0], index=["a", "b", "c"]),
    "two": pd.Series([1.0, 2.0, 3.0, 4.0], index=["a", "b", "c", "d"]),
}
print(pd.DataFrame(d))
print(pd.DataFrame(d, index=["d", "b", "a"]))
print(pd.DataFrame(d, index=["d", "b", "a"], columns=["two", "three"]))
print(10 * '*')
d = {"one": [1.0, 2.0, 3.0, 4.0], "two": [4.0, 3.0, 2.0, 1.0]}
print(pd.DataFrame(d))
print(10 * '*')
data2 = [{"a": 1, "b": 2}, {"a": 5, "b": 10, "c": 20}]
print(pd.DataFrame(data2))
print(10 * '*')
print(pd.DataFrame(np.random.randn(6, 3), index=list('abcdef'), columns=['first', 'second', 'third']))

   one  two
a  1.0  1.0
b  2.0  2.0
c  3.0  3.0
d  NaN  4.0
   one  two
d  NaN  4.0
b  2.0  2.0
a  1.0  1.0
   two three
d  4.0   NaN
b  2.0   NaN
a  1.0   NaN
**********
   one  two
0  1.0  4.0
1  2.0  3.0
2  3.0  2.0
3  4.0  1.0
**********
   a   b     c
0  1   2   NaN
1  5  10  20.0
**********
      first    second     third
a  1.552886  0.923738 -1.249404
b -0.779500 -0.771745  0.391670
c  0.226004  1.246042  0.135406
d  1.037689 -1.609049 -0.103743
e -0.126385  0.365205  0.555974
f  1.385454  0.589635 -0.539962


We can add new columns.

In [ ]:
df = pd.DataFrame(np.random.randn(6, 3), index=list('abcdef'), columns=['first', 'second', 'third'])
df.insert(1, "bar", df["first"])
df.insert(4, "last", 5.0)
df.insert(5, "actually_last", ['car', 'tram', 'bus', 'car', 'bike', 'car'])
print(df)

      first       bar    second     third  last actually_last
a -1.926596 -1.926596 -0.728207  0.668471   5.0           car
b  0.053308  0.053308  1.071343 -1.381567   5.0          tram
c  1.039376  1.039376  1.250617  2.215683   5.0           bus
d -0.514517 -0.514517 -1.435444  0.111954   5.0           car
e -1.030886 -1.030886 -1.551924  0.175286   5.0          bike
f  1.072846  1.072846  1.343546  0.666972   5.0           car


We can also create a new column from existing columns.

In [ ]:
print(df.assign(new_column=df["first"] / df["second"]))

      first       bar    second     third  last actually_last  new_column
a -1.926596 -1.926596 -0.728207  0.668471   5.0           car    2.645672
b  0.053308  0.053308  1.071343 -1.381567   5.0          tram    0.049758
c  1.039376  1.039376  1.250617  2.215683   5.0           bus    0.831091
d -0.514517 -0.514517 -1.435444  0.111954   5.0           car    0.358437
e -1.030886 -1.030886 -1.551924  0.175286   5.0          bike    0.664263
f  1.072846  1.072846  1.343546  0.666972   5.0           car    0.798518


Indexing can be performed in multiple ways:
* Select column `df[col]`
* Select row by label `df.loc[label]`
* Select row by integer location `df.iloc[loc]`
* Slice rows `df[5:10]`
* Select rows by boolean vector `df[bool_vec]`


In [ ]:
print(df['first'])
print(df.loc['b'])
print(df.iloc[2])

a   -1.926596
b    0.053308
c    1.039376
d   -0.514517
e   -1.030886
f    1.072846
Name: first, dtype: float64
first            0.053308
bar              0.053308
second           1.071343
third           -1.381567
last                  5.0
actually_last        tram
Name: b, dtype: object
first            1.039376
bar              1.039376
second           1.250617
third            2.215683
last                  5.0
actually_last         bus
Name: c, dtype: object


We can also perform operations on dataframes. Most NumPy functions work as well.

In [ ]:
df2 = df[['first', 'bar', 'second']]
print(df2)
print(2 * df2 + 1.0)
print(df2 - df2.iloc[0])
print(np.exp(df2))

      first       bar    second
a -1.926596 -1.926596 -0.728207
b  0.053308  0.053308  1.071343
c  1.039376  1.039376  1.250617
d -0.514517 -0.514517 -1.435444
e -1.030886 -1.030886 -1.551924
f  1.072846  1.072846  1.343546
      first       bar    second
a -2.853192 -2.853192 -0.456413
b  1.106616  1.106616  3.142685
c  3.078752  3.078752  3.501233
d -0.029033 -0.029033 -1.870888
e -1.061771 -1.061771 -2.103849
f  3.145693  3.145693  3.687093
      first       bar    second
a  0.000000  0.000000  0.000000
b  1.979904  1.979904  1.799549
c  2.965972  2.965972  1.978823
d  1.412079  1.412079 -0.707238
e  0.895710  0.895710 -0.823718
f  2.999442  2.999442  2.071753
      first       bar    second
a  0.145643  0.145643  0.482774
b  1.054755  1.054755  2.919296
c  2.827452  2.827452  3.492496
d  0.597789  0.597789  0.238010
e  0.356691  0.356691  0.211840
f  2.923690  2.923690  3.832611


We can also load a csv. We will first download one.

In [ ]:
!wget https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data
!wget https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.names
!tail -n 16 adult.names

--2022-03-13 23:43:07--  https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3974305 (3.8M) [application/x-httpd-php]
Saving to: ‘adult.data’

adult.data          100%[===================>]   3.79M  3.13MB/s    in 1.2s    

2022-03-13 23:43:09 (3.13 MB/s) - ‘adult.data’ saved [3974305/3974305]

--2022-03-13 23:43:09--  https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.names
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5229 (5.1K) [application/x-httpd-php]
Saving to: ‘adult.names’

adult.names         100%[===================>]   5.11K  --.-KB/s    in 0s      

2022-

In [ ]:
data = pd.read_csv('adult.data', header=None)
print(data)
print(data.iloc[0])

       0                  1       2            3   4                    5   \
0      39          State-gov   77516    Bachelors  13        Never-married   
1      50   Self-emp-not-inc   83311    Bachelors  13   Married-civ-spouse   
2      38            Private  215646      HS-grad   9             Divorced   
3      53            Private  234721         11th   7   Married-civ-spouse   
4      28            Private  338409    Bachelors  13   Married-civ-spouse   
...    ..                ...     ...          ...  ..                  ...   
32556  27            Private  257302   Assoc-acdm  12   Married-civ-spouse   
32557  40            Private  154374      HS-grad   9   Married-civ-spouse   
32558  58            Private  151910      HS-grad   9              Widowed   
32559  22            Private  201490      HS-grad   9        Never-married   
32560  52       Self-emp-inc  287927      HS-grad   9   Married-civ-spouse   

                       6               7       8        9      

## Information Theory Measures

We have covered these measures during the lecture. Now we will try to implement them in code.

### Exercise 2 - Shannon Entropy

Shannon entropy is defined as: $H(Y) = - \sum_{y \in \omega} P(Y = y) \cdot log_2(P(Y = y))$

Implement the Shannon Entropy as the function entropy. Its only input will be a Pandas Series object.

*Note:* You can calculate the probabilities by calculating how many times a given value occurs in the given series. In order to do that you may want to use the `value_counts` method of the `Series` class.

In [ ]:
def entropy(s):
  v = s.value_counts(normalize=True).to_numpy()
  entropy = np.sum(-v * np.log2(v))
  return entropy

If you implemented these correctly these tests should run.

In [ ]:
print(entropy(data[0]))
print(entropy(data[13]))

5.68332439640033
0.9437954138017222


### Exercise 3 - Conditional Entropy

We can recap the definition of the conditinal entropy.

Specific conditional entropy: $H(Y| X = v) = H(Y),$ only for values of $Y$, where $X = x$

Conditional Entropy: $H(Y| X) = \sum_{x \in \Omega_x} P(X = x) \cdot H(Y | X = x)$

Now we will implement the function `conditional_entropy` which will take two `Series` objects as inputs.

*Note:* You want to sum over the categories of y. Therefore, it is useful to convert that `Series` object into `category` type using the `astype` method. You can then obtain a list of the categories in the `Series`, try to google how.

In [ ]:
def conditional_entropy(y, x):
  ce = 0
  x = x.astype('category')
  cats = x.cat.categories
  p = x.value_counts(normalize=True)

  for cat in cats:
    ce += p[cat] * entropy(y[x == cat])
  return ce


These tests should run successfully if your implementation is correct.

In [ ]:
print(conditional_entropy(data[13], data[14]))
print(conditional_entropy(data[1], data[14]))
print(conditional_entropy(data[8], data[14]))
print(conditional_entropy(data[3], data[14]))

0.9351000717808609
1.626405337311804
0.7903627046854481
2.837760056715097
