<a href="https://colab.research.google.com/github/kocurvik/edu/blob/master/RO/cvicenia/notebooky/cv04_en.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **4. lab** - Google Colab, NumPy and Pandas Basics, Feature Entropy

In this notebook we will cover the basics of working in the Google Colab environment, NumPy and basic image manipulation in OpenCV.

## Google Colab

Google Colab (http://colab.research.google.com) is a free service which allows the users to run ipython notebooks in the cloud. The service also allows the users to leverage a free GPU. A Google account is necessary to use this service. The notebooks can also be downloaded and run locally using the jupyter notebook in the directory where the notebooks are saved (provided you have jupyter installed).

There are two types of cells in these notbooks. The first type is a text cell such as this one. The other type of a cell is code cell. The cells with code can be run with the play button to the left of the cell. All of the cells can also be run by clicking choosing Runtime -> Run All in the menu at the top of this page. The cells share a scope so it is necessary to be mindful of the order in which the cells run. If you need to restart the notebook you can look into the Runtime tab in the options on top of the page.

You can try running a simple python code in the following cell.

In [ ]:
a = [5,'Hello']
s = '{} World!'
print(s.format(a[1]))

def najlepsia_funkcia(arg):
  return arg + 5

print(najlepsia_funkcia(8))

Hello World!
13


Saving and using files that are stored permanently can be done in different ways, but the easiest option is to connecting Google Drive to our notebook instance. This is done in a following way:
(Note: this assumes that you have created a directory named Colab in your Google Drive)

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')
root_path = 'gdrive/My Drive/Colab/'

Mounted at /content/gdrive


You can then access the folder (if it exists).

In [ ]:
import os
os.listdir(root_path)

['mnist-fc-trained.h5', 'cifar-fc-trained.h5']

You can also use the standard unix commands by preceeding them with an exclamation point.

In [ ]:
!pwd
!ls
!mkdir random_dir
!ls
!wget https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png
!ls

/content
gdrive	sample_data
gdrive	random_dir  sample_data
--2022-03-07 21:46:31--  https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png
Resolving www.google.com (www.google.com)... 74.125.26.105, 74.125.26.147, 74.125.26.106, ...
Connecting to www.google.com (www.google.com)|74.125.26.105|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5969 (5.8K) [image/png]
Saving to: ‘googlelogo_color_272x92dp.png’

googlelogo_color_27 100%[===================>]   5.83K  --.-KB/s    in 0s      

2022-03-07 21:46:31 (55.1 MB/s) - ‘googlelogo_color_272x92dp.png’ saved [5969/5969]

gdrive	googlelogo_color_272x92dp.png  random_dir  sample_data


This is not always necessary as you can access the instance file structure in the panel on the left.

**<----**

## NumPy
A tensor is a base data structure we will use when dealing with neural networks. Tensor is a generalization of vectors and matrices. Vectors from $\mathbb{R}^n$ are first order (rank) tensors and matrices are second order (rank) tensors. A third order (rank) tensor can be additionally indexed with one more index. Sometimes the order of tensor is also called its rank. Strictly speaking tensor dimension and order are two different concepts. For example, we can have a third order tensor with dimension $ 20 \times 24 \times 6$. However, in many texts authors interchange tensor order (rank) with dimension. This is sometimes confusing, but usually the meaning is evident from context.

To conform to standards we import numpy as np. A vector (e.g. first order tensor) can be created from a simple list using the np.array constructor. It might be important to initialize the array with a specific data type which can be done by using the dtype keyword in the constructor. **Not specifying the dtype can cause various complications later in the code.**


In [ ]:
import numpy as np

a = np.array([3, 2, 3, 4])
print(a)
b = np.array([1,5,7], dtype=np.float32)
print(b)

[3 2 3 4]
[1. 5. 7.]


A matrix can be created from a list of lists, but it is necessary for the lengths of the inner lists to be consitent. If they are not consistent we will obtain a vector of lists instead of matrix of values.

In [ ]:
A = np.array([[1,5,8],[50,60,84]])
print(A)
B = np.array([[7,8],[6,7],[0,9,4]])
print(B)

[[ 1  5  8]
 [50 60 84]]
[list([7, 8]) list([6, 7]) list([0, 9, 4])]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  This is separate from the ipykernel package so we can avoid doing imports until


The array object has a shape method which tells us its shape (dimensions) and method dtype which returns the data type of the values in the tensor. It also has a method astype which returns an array with the specified type.

In [ ]:
print(a.shape)
print(A.shape)
print(A.dtype)
C = A.astype(np.float32)
print(C.dtype)


(4,)
(2, 3)
int64
float32


Numpy has a few functions to generate basic tensors. The most commnly used onse are: np.zeros, np.ones and np.empty.

In [ ]:
z = np.zeros([5,10])
print(z)
o = np.ones([3,4,5])
print(o)
e = np.empty([6])
print(e)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
[4.65503808e-310 4.65503615e-310 4.94065646e-324             nan
 0.00000000e+000 0.00000000e+000]


It is also possible the create tensors with random numbers by using np.random.random.

In [ ]:
r = np.random.random([6,10,3])
print(r)

[[[0.37609057 0.27399519 0.45095456]
  [0.95515759 0.29432465 0.73140622]
  [0.48452713 0.97236008 0.6465912 ]
  [0.44375435 0.26019661 0.43845583]
  [0.60811179 0.6566053  0.8759779 ]
  [0.66348412 0.67583621 0.73478718]
  [0.62373612 0.29464245 0.73163286]
  [0.73504665 0.31342011 0.70098394]
  [0.13749185 0.96304362 0.86000473]
  [0.114123   0.72868242 0.42138606]]

 [[0.06776839 0.68421728 0.23709622]
  [0.59042062 0.41267923 0.05880186]
  [0.81659239 0.23075196 0.61386827]
  [0.10831952 0.78947864 0.34207873]
  [0.64632223 0.92758779 0.29214563]
  [0.62083822 0.67338938 0.76254014]
  [0.52657551 0.67532466 0.4418122 ]
  [0.79623088 0.68132658 0.80379401]
  [0.14112973 0.34945303 0.07610923]
  [0.38427983 0.99711358 0.33463559]]

 [[0.91466172 0.17365396 0.83180722]
  [0.61133419 0.07174696 0.3986415 ]
  [0.16354495 0.30037022 0.87726443]
  [0.67928526 0.76840642 0.54958239]
  [0.31345422 0.56903988 0.81312469]
  [0.90418554 0.76384634 0.88869074]
  [0.10549558 0.05924047 0.2745575

We can now use these random arrays to work with indices. Indexing is similar to Matlab, but the python conventions are applied. We can use multiple indices (based on tensor order). If we omit one of the indices it is implicitly used as :, which means that all of the elements along that dimesnsions are used.

In [ ]:
print(r[3,4,1])
print(r[:,:,-1])
print(r[:,:,1].shape)
print(r[0:4,5:6,:])
print(r[0:4,5:6,:].shape)

0.35844851964802005
[[0.45095456 0.73140622 0.6465912  0.43845583 0.8759779  0.73478718
  0.73163286 0.70098394 0.86000473 0.42138606]
 [0.23709622 0.05880186 0.61386827 0.34207873 0.29214563 0.76254014
  0.4418122  0.80379401 0.07610923 0.33463559]
 [0.83180722 0.3986415  0.87726443 0.54958239 0.81312469 0.88869074
  0.27455753 0.18365623 0.1381183  0.10256029]
 [0.73980084 0.24591847 0.01040102 0.72170894 0.45086515 0.44478381
  0.12310213 0.72353175 0.2260814  0.78744722]
 [0.55817117 0.28172263 0.73339805 0.07573307 0.22831284 0.83501359
  0.10905797 0.05554133 0.65639557 0.64007553]
 [0.4610274  0.011317   0.80696909 0.63375063 0.40675631 0.76649494
  0.04798971 0.3134773  0.32380675 0.3676341 ]]
(6, 10)
[[[0.66348412 0.67583621 0.73478718]]

 [[0.62083822 0.67338938 0.76254014]]

 [[0.90418554 0.76384634 0.88869074]]

 [[0.88511982 0.44540243 0.44478381]]]
(4, 1, 3)


We can also use steps when indexing this is also called slicing. That can be done by another colon. The format is then [start:stop:step]. If any of that is left empty the start is implicitly assumed to be 0, the end -1 and step 1.

In [ ]:
p = np.arange(25)
print(p)
print(p[4:16:2])
print(p[2:-4:6])
print(p[:10:])
print(p[::3])
print(p[1::6])
print(p[-6:])
print(r[1::2,0::3,:])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[ 4  6  8 10 12 14]
[ 2  8 14 20]
[0 1 2 3 4 5 6 7 8 9]
[ 0  3  6  9 12 15 18 21 24]
[ 1  7 13 19]
[19 20 21 22 23 24]
[[[0.06776839 0.68421728 0.23709622]
  [0.10831952 0.78947864 0.34207873]
  [0.52657551 0.67532466 0.4418122 ]
  [0.38427983 0.99711358 0.33463559]]

 [[0.27066993 0.5145716  0.73980084]
  [0.18811456 0.28365258 0.72170894]
  [0.38513017 0.91050494 0.12310213]
  [0.7782701  0.98720414 0.78744722]]

 [[0.66495657 0.00787319 0.4610274 ]
  [0.19216521 0.33429736 0.63375063]
  [0.5000918  0.93669946 0.04798971]
  [0.33697418 0.8958177  0.3676341 ]]]


We will often need to create a so-called singleton dimension. This cane be done by adding a None index, or in a more python way by using np.newaxis.

In [ ]:
print(r[None,:,:,:].shape)
print(r[None].shape)
print(r[np.newaxis,:,:,:].shape)
print(r[:,:,:,np.newaxis].shape)
print(r[np.newaxis,:,0,:].shape)

(1, 6, 10, 3)
(1, 6, 10, 3)
(1, 6, 10, 3)
(6, 10, 3, 1)
(1, 6, 3)


Similar to Matlab broadcasting is done implicitly (though different rules are applied in Matlab).

In [ ]:
r += 10
print(r)
r[0,:,:] = np.random.random([10,3])
print(r.shape)
r[0] = np.random.random([10,3])
print(r.shape)
r[0] = np.zeros([10,1])
print(r.shape)
r/=500
print(r)

[[[10.37609057 10.27399519 10.45095456]
  [10.95515759 10.29432465 10.73140622]
  [10.48452713 10.97236008 10.6465912 ]
  [10.44375435 10.26019661 10.43845583]
  [10.60811179 10.6566053  10.8759779 ]
  [10.66348412 10.67583621 10.73478718]
  [10.62373612 10.29464245 10.73163286]
  [10.73504665 10.31342011 10.70098394]
  [10.13749185 10.96304362 10.86000473]
  [10.114123   10.72868242 10.42138606]]

 [[10.06776839 10.68421728 10.23709622]
  [10.59042062 10.41267923 10.05880186]
  [10.81659239 10.23075196 10.61386827]
  [10.10831952 10.78947864 10.34207873]
  [10.64632223 10.92758779 10.29214563]
  [10.62083822 10.67338938 10.76254014]
  [10.52657551 10.67532466 10.4418122 ]
  [10.79623088 10.68132658 10.80379401]
  [10.14112973 10.34945303 10.07610923]
  [10.38427983 10.99711358 10.33463559]]

 [[10.91466172 10.17365396 10.83180722]
  [10.61133419 10.07174696 10.3986415 ]
  [10.16354495 10.30037022 10.87726443]
  [10.67928526 10.76840642 10.54958239]
  [10.31345422 10.56903988 10.813124

An array can be reshaped using np.reshape

In [ ]:
q = np.reshape(r, [6,30])
print(q.shape)

(6, 30)


Arrays can be joined. One way is to use np.concatenate([arr1, arr2, ...], axis = i) which connects the arrays arr1 and arr2 through a given axis i. Note that is usually better (for code comprehension) to explicitly use the keyword axis even if it is redundant.

In [ ]:
a = np.ones([3,4])
b = np.zeros([6,4])
c = np.concatenate([a,b], axis = 0)
print(c)                   

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


A different option is to use np.stack([arr1, arr2, ...], axis= i). The difference is that this creates increases the tensor order by one.

In [ ]:
a = np.ones([6,4,3])
b = np.zeros([6,4,3])
d = np.stack([a,b], axis = 0)
print(d.shape)
f = np.stack([a,b], axis = -1)
print(f.shape)
g = np.stack([a,b], axis = 1)
print(g.shape)

(2, 6, 4, 3)
(6, 4, 3, 2)
(6, 2, 4, 3)


We can also index using conditions.

In [ ]:
r = np.random.random([5,5])
print(r)
r[r < 0.5] = -500
print(r)

[[0.84661986 0.52590421 0.99005208 0.47280933 0.83191307]
 [0.95619877 0.51263073 0.07720779 0.25490333 0.44293133]
 [0.07596246 0.56996753 0.03464115 0.38871377 0.55586237]
 [0.81317365 0.80039007 0.79035552 0.10335248 0.33667092]
 [0.17062827 0.08063663 0.34987135 0.28444584 0.304514  ]]
[[   0.84661986    0.52590421    0.99005208 -500.            0.83191307]
 [   0.95619877    0.51263073 -500.         -500.         -500.        ]
 [-500.            0.56996753 -500.         -500.            0.55586237]
 [   0.81317365    0.80039007    0.79035552 -500.         -500.        ]
 [-500.         -500.         -500.         -500.         -500.        ]]


The conditions can also be using in np.whare(cond, a1, a2), which returns an array which contans elemnts from a1 where the condition is true and elements from a2 where condition is false. We can also use np.arange(i) which is equivalent to range(i) from python.

In [ ]:
a = np.arange(10)
print(a)
b = np.where(a < 5, a, a**2)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4 25 36 49 64 81]


### Exercise 1
Create a funciton chessboard(rows, cols) which returns a numpy array with dimensions rows x cols. The array will contain 1 in spots where a chessboard tile would be white and 0 where a chessboard tile would be black.

The simplest way is to use slicing. If you feel adventurous you can check the NumPy documentation and use conditions with np.mgrid or repetition and np.tile.

In [ ]:
def chessboard(rows, cols):
  ...

In [ ]:
print(chessboard(8,8))
print(chessboard(5,12))

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]
[[0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]]


### NumPy Documentation
We will go through some basic linear algebra and statistics operations with NumPy during the next lab. 

If you are curious you can check out the documentation of NumPy: https://docs.scipy.org/doc/numpy/

## Introduction to Pandas
We will use the pandas library to store our data. If we only used numerical features we would be fine with just NumPy, but this is usually not sufficient for categorical data or more complex structures. More info on Pandas data structures can be found in [this user guide](https://pandas.pydata.org/pandas-docs/stable/user_guide/dsintro.html#dsintro)

In [ ]:
import pandas as pd
import numpy as np

### Series

One of the basic datatypes is Series. It is essentially a more sophisticated 1-d array of data, which can include named indices.

In [ ]:
s = pd.Series(np.random.randn(5))
print(s)

s = pd.Series(np.random.randn(5), index=["a", "b", "c", "d", "e"])
print(s)

d = {"a": 0.0, "b": 1.0, "c": 2.0}
print(pd.Series(d))
print(pd.Series(d, index=["b", "c", "d", "a"]))

0   -0.041573
1    0.093297
2    1.596013
3   -1.029345
4    0.737356
dtype: float64
a    0.428387
b   -0.245977
c   -1.351491
d    0.238107
e    1.170731
dtype: float64
a    0.0
b    1.0
c    2.0
dtype: float64
b    1.0
c    2.0
d    NaN
a    0.0
dtype: float64


In many cases Series can be used in place of standard NumPy array.

In [ ]:
print(s.dtype)
print(s.shape)
print(s[0])
print(s[:3])
print(np.sum(s))
print(np.exp(s))

float64
(5,)
0.4283869816460045
a    0.428387
b   -0.245977
c   -1.351491
dtype: float64
0.23975634205703844
a    1.534780
b    0.781940
c    0.258854
d    1.268845
e    3.224350
dtype: float64


We can convert Series to a NumPy array.

In [ ]:
print(s.to_numpy())

[ 0.42838698 -0.24597742 -1.35149132  0.23810671  1.17073139]


We can also perform indexing and standard operations on Series.

In [ ]:
print(2.5 * s + s)
print(s[s > s.median()])
print(s[[4, 3, 1]])

a    1.499354
b   -0.860921
c   -4.730220
d    0.833373
e    4.097560
dtype: float64
a    0.428387
e    1.170731
dtype: float64
e    1.170731
d    0.238107
b   -0.245977
dtype: float64


But beware! Operations rely on the defined indexes! This is different from NumPy.

In [ ]:
print(s[1:] + s[:-1])
n = s.to_numpy()
print(n[1:] + n[:-1])

a         NaN
b   -0.491955
c   -2.702983
d    0.476213
e         NaN
dtype: float64
[ 0.18240956 -1.59746874 -1.1133846   1.4088381 ]


A Series also behaves as a dict!

In [ ]:
print(s["a"])
s["c"] = 0.2
print(s)

0.4283869816460045
a    0.428387
b   -0.245977
c    0.200000
d    0.238107
e    1.170731
dtype: float64


### DataFrames

DataFrame is a 2-d structure of data. We will mostly use this structure!

It can be constructed from:

* Dict of 1D ndarrays, lists, dicts, or Series
* 2-D numpy.ndarray
* Structured or record ndarray
* A Series
* Another DataFrame

In [ ]:
d = {
    "one": pd.Series([1.0, 2.0, 3.0], index=["a", "b", "c"]),
    "two": pd.Series([1.0, 2.0, 3.0, 4.0], index=["a", "b", "c", "d"]),
}
print(pd.DataFrame(d))
print(pd.DataFrame(d, index=["d", "b", "a"]))
print(pd.DataFrame(d, index=["d", "b", "a"], columns=["two", "three"]))
print(10 * '*')
d = {"one": [1.0, 2.0, 3.0, 4.0], "two": [4.0, 3.0, 2.0, 1.0]}
print(pd.DataFrame(d))
print(10 * '*')
data2 = [{"a": 1, "b": 2}, {"a": 5, "b": 10, "c": 20}]
print(pd.DataFrame(data2))
print(10 * '*')
print(pd.DataFrame(np.random.randn(6, 3), index=list('abcdef'), columns=['first', 'second', 'third']))

   one  two
a  1.0  1.0
b  2.0  2.0
c  3.0  3.0
d  NaN  4.0
   one  two
d  NaN  4.0
b  2.0  2.0
a  1.0  1.0
   two three
d  4.0   NaN
b  2.0   NaN
a  1.0   NaN
**********
   one  two
0  1.0  4.0
1  2.0  3.0
2  3.0  2.0
3  4.0  1.0
**********
   a   b     c
0  1   2   NaN
1  5  10  20.0
**********
      first    second     third
a  0.564167  0.521180  0.273723
b -0.268375  0.103838 -0.680243
c  0.930615  0.476973  0.022860
d -0.455305 -0.718255 -1.577767
e -0.639825 -0.030335 -0.738020
f  1.372504 -0.635552 -0.892707


We can add new columns.

In [ ]:
df = pd.DataFrame(np.random.randn(6, 3), index=list('abcdef'), columns=['first', 'second', 'third'])
df.insert(1, "bar", df["first"])
df.insert(4, "last", 5.0)
df.insert(5, "actually_last", ['car', 'tram', 'bus', 'car', 'bike', 'car'])
print(df)

      first       bar    second     third  last actually_last
a -0.594906 -0.594906  0.745969 -1.837952   5.0           car
b -0.724108 -0.724108 -2.305174  1.336821   5.0          tram
c  1.264896  1.264896  0.353127 -0.791034   5.0           bus
d -0.492862 -0.492862 -0.530776 -0.873550   5.0           car
e  1.330198  1.330198  0.934563  0.589562   5.0          bike
f -0.512410 -0.512410 -0.587806 -0.681344   5.0           car


We can also create a new column from existing columns.

In [ ]:
print(df.assign(new_column=df["first"] / df["second"]))

      first       bar    second     third  last actually_last  new_column
a -0.594906 -0.594906  0.745969 -1.837952   5.0           car   -0.797494
b -0.724108 -0.724108 -2.305174  1.336821   5.0          tram    0.314123
c  1.264896  1.264896  0.353127 -0.791034   5.0           bus    3.581983
d -0.492862 -0.492862 -0.530776 -0.873550   5.0           car    0.928568
e  1.330198  1.330198  0.934563  0.589562   5.0          bike    1.423337
f -0.512410 -0.512410 -0.587806 -0.681344   5.0           car    0.871734


Indexing can be performed in multiple ways:
* Select column `df[col]`
* Select row by label `df.loc[label]`
* Select row by integer location `df.iloc[loc]`
* Slice rows `df[5:10]`
* Select rows by boolean vector `df[bool_vec]`


In [ ]:
print(df['first'])
print(df.loc['b'])
print(df.iloc[2])

a   -0.594906
b   -0.724108
c    1.264896
d   -0.492862
e    1.330198
f   -0.512410
Name: first, dtype: float64
first           -0.724108
bar             -0.724108
second          -2.305174
third            1.336821
last                  5.0
actually_last        tram
Name: b, dtype: object
first            1.264896
bar              1.264896
second           0.353127
third           -0.791034
last                  5.0
actually_last         bus
Name: c, dtype: object


We can also perform operations on dataframes. Most NumPy functions work as well.

In [ ]:
df2 = df[['first', 'bar', 'second']]
print(df2)
print(2 * df2 + 1.0)
print(df2 - df2.iloc[0])
print(np.exp(df2))

      first       bar    second
a -0.594906 -0.594906  0.745969
b -0.724108 -0.724108 -2.305174
c  1.264896  1.264896  0.353127
d -0.492862 -0.492862 -0.530776
e  1.330198  1.330198  0.934563
f -0.512410 -0.512410 -0.587806
      first       bar    second
a -0.189813 -0.189813  2.491939
b -0.448215 -0.448215 -3.610349
c  3.529792  3.529792  1.706255
d  0.014276  0.014276 -0.061552
e  3.660397  3.660397  2.869127
f -0.024820 -0.024820 -0.175611
      first       bar    second
a  0.000000  0.000000  0.000000
b -0.129201 -0.129201 -3.051144
c  1.859802  1.859802 -0.392842
d  0.102044  0.102044 -1.276746
e  1.925105  1.925105  0.188594
f  0.082496  0.082496 -1.333775
      first       bar    second
a  0.551614  0.551614  2.108484
b  0.484757  0.484757  0.099741
c  3.542723  3.542723  1.423512
d  0.610876  0.610876  0.588148
e  3.781794  3.781794  2.546101
f  0.599050  0.599050  0.555545


We can also load a csv. We will first download one.

In [ ]:
!wget https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data
!wget https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.names
!tail -n 16 adult.names

--2022-03-07 21:46:33--  https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3974305 (3.8M) [application/x-httpd-php]
Saving to: ‘adult.data’

adult.data          100%[===================>]   3.79M  6.60MB/s    in 0.6s    

2022-03-07 21:46:34 (6.60 MB/s) - ‘adult.data’ saved [3974305/3974305]

--2022-03-07 21:46:34--  https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.names
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5229 (5.1K) [application/x-httpd-php]
Saving to: ‘adult.names’

adult.names         100%[===================>]   5.11K  --.-KB/s    in 0s      

2022-

In [ ]:
data = pd.read_csv('adult.data', header=None)
print(data)
print(data.iloc[0])

       0                  1       2            3   4                    5   \
0      39          State-gov   77516    Bachelors  13        Never-married   
1      50   Self-emp-not-inc   83311    Bachelors  13   Married-civ-spouse   
2      38            Private  215646      HS-grad   9             Divorced   
3      53            Private  234721         11th   7   Married-civ-spouse   
4      28            Private  338409    Bachelors  13   Married-civ-spouse   
...    ..                ...     ...          ...  ..                  ...   
32556  27            Private  257302   Assoc-acdm  12   Married-civ-spouse   
32557  40            Private  154374      HS-grad   9   Married-civ-spouse   
32558  58            Private  151910      HS-grad   9              Widowed   
32559  22            Private  201490      HS-grad   9        Never-married   
32560  52       Self-emp-inc  287927      HS-grad   9   Married-civ-spouse   

                       6               7       8        9      

## Information Theory Measures

We have covered these measures during the lecture. Now we will try to implement them in code.

### Exercise 2 - Shannon Entropy

Shannon entropy is defined as: $H(Y) = - \sum_{y \in \omega} P(Y = y) \cdot log_2(P(Y = y))$

Implement the Shannon Entropy as the function entropy. Its only input will be a Pandas Series object.

*Note:* You can calculate the probabilities by calculating how many times a given value occurs in the given series. In order to do that you may want to use the `value_counts` method of the `Series` class.

In [ ]:
def entropy(s):
  ...

If you implemented these correctly these tests should run.

In [ ]:
print(entropy(data[0]))
print(entropy(data[13]))

5.68332439640033
0.9437954138017222


### Exercise 3 - Conditional Entropy

We can recap the definition of the conditinal entropy.

Specific conditional entropy: $H(Y| X = v) = H(Y),$ only for values of $Y$, where $X = x$

Conditional Entropy: $H(Y| X) = \sum_{x \in \Omega_x} P(X = x) \cdot H(Y | X = x)$

Now we will implement the function `conditional_entropy` which will take two `Series` objects as inputs.

*Note:* You want to sum over the categories of y. Therefore, it is useful to convert that `Series` object into `category` type using the `astype` method. You can then obtain a list of the categories in the `Series`, try to google how.

In [ ]:
def conditional_entropy(y, x):
  ...

These tests should run successfully if your implementation is correct.

In [ ]:
print(conditional_entropy(data[13], data[14]))
print(conditional_entropy(data[1], data[14]))
print(conditional_entropy(data[8], data[14]))
print(conditional_entropy(data[3], data[14]))

0.787688613181352
0.7748123650040903
0.7880060088737025
0.7027931141135986
